In [1]:
from Bio import SeqIO
import pandas as pd

In [33]:

# FASTA file UP000006548_3702.fasta arabidopsis thaliana from Uniprot
fasta_file = "/home/wenyuantong/Desktop/data/UP000006548_3702.fasta"

# Create lists to store data
names = []
sequences = []
lengths = []

# Parse the FASTA file
for record in SeqIO.parse(fasta_file, "fasta"):
    names.append(record.description)
    sequences.append(str(record.seq))
    lengths.append(len(record.seq))

# Create a pandas DataFrame
data = {'Name': names, 'Sequence_protein': sequences, 'Sequence Length': lengths}
df = pd.DataFrame(data)

# Display the DataFrame
display(df.head())

,Name,Sequence_protein,Sequence Length
0,tr|A0A1I9LPH3|A0A1I9LPH3_ARATH Uncharacterized...,REEVFSDVPLWLRQRPAFLVVLLLTEEEEEEDEEDLQVYIKWSHNP...,50
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854
2,"sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3, ch...",MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPSLWQHEYLLSLGN...,565
3,tr|B3H6N5|B3H6N5_ARATH Uncharacterized protein...,MESIRSYIVASMDIDIPDQSVTEMNCLCLDLKLMGLG,37
4,tr|F4I2G0|F4I2G0_ARATH Ankyrin-repeat containi...,MGFTFTKIYTSSAPDLGITGLVKKAVFIVFLVCNSIPVLLSVIATM...,107

NameError: name 'df' is not defined

In [18]:
# Replace 'your_file.csv' with the actual path to your CSV file
try:
    df_IDR = pd.read_csv('~/Desktop/data/filtered_IDR_Arabi.csv')
    # Assuming the column with lengths is the first column (index 0)
    # You might need to change '0' to the actual column name or index if different
except FileNotFoundError:
    print("Error: 'your_file.csv' not found. Please replace with the correct file path.")
except Exception as e:
    print(f"An error occurred: {e}")

In [19]:
display(df_IDR)

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,FCR,NCPR,kappa,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence
0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride l...,1,66,66,23.80,55.49,0.404,0.535,7.015,0.273,0.121,0.212,0.076,0.197,0.121,0.076,0.303,0.212,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPN...
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride l...,306,525,220,47.99,115.33,0.419,0.569,5.882,0.286,-0.095,0.176,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...
2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; c...,1,34,34,16.55,40.86,0.455,0.568,6.505,0.294,0.235,0.297,0.029,0.265,0.059,0.118,0.382,0.147,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPS
3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pr...,1,292,292,54.52,122.24,0.427,0.552,6.358,0.288,-0.041,0.179,0.164,0.123,0.058,0.027,0.384,0.240,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLIS...
4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pr...,415,496,82,28.27,67.04,0.438,0.561,6.196,0.390,-0.049,0.150,0.220,0.171,0.012,0.085,0.317,0.195,DNKNAYKPREGDSEHKEKPMQQIESLEGDDGADKSTHREKEKEAP...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23611,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-...,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain...,332,540,209,44.63,104.93,0.410,0.544,6.643,0.258,-0.029,0.182,0.144,0.115,0.067,0.086,0.373,0.211,KEKGKVPDKYRTNQTTERELSPTGLDSSPRDVLGGRGFYNNTQDV...
23612,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabido...,1,49,49,19.85,47.41,0.455,0.528,6.362,0.163,-0.041,0.308,0.102,0.061,0.061,0.041,0.490,0.224,MNDLLSGSFKTSVADGSSPPHSHNIEMSKAKVSGGSCHGGNNLDT...
23613,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabido...,309,341,33,16.79,41.34,0.484,0.529,7.678,0.152,0.091,0.540,0.030,0.121,0.000,0.212,0.394,0.242,ESNGGGGGGAPRQATPVQAQPPPPPAVNRRLLR
23614,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein l...,1,115,115,29.11,68.63,0.406,0.536,6.129,0.043,0.009,0.331,0.017,0.026,0.104,0.035,0.548,0.261,MAKWFFTIFLVFALASALACGARNVPVGLSDQKNYLGYGGGYSGV...
23615,sp|Q9XFB0|YAB2_ARATH Putative axial regulator ...,sp|Q9XFB0|YAB2_ARATH Putative axial regulator...,1,115,115,32.47,79.28,0.407,0.541,6.625,0.174,0.035,0.134,0.070,0.104,0.043,0.078,0.374,0.278,MSVDFSSERVCYVHCSFCTTILAVSVPYASLFTLVTVRCGHCTNL...

In [20]:


# Find the maximum value in 'col1'
max_value_col1 = df_IDR[' IDR len'].max()

print(f"\nMaximum value in 'col1': {max_value_col1}")

Maximum value in 'col1': 2889

In [21]:
# Find the median value in 'col1'
median_value_col1 = df_IDR[' IDR len'].median()

print(f"Median value in 'col1': {median_value_col1}")

Median value in 'col1': 75.0

In [35]:
#df_IDR[' FASTA header'] = df_IDR[' FASTA header'].str[1:]

df_IDR[' FASTA header'] = df_IDR[' FASTA header'].str.lstrip()

#print(f"\nDataFrame after removing leading spaces from the '{column_to_modify}' column:")
#display(df)

In [46]:
# Iterate through each column
#for Name in df.Name:
    # Apply replacement only if the column contains strings

df['Name'] = df['Name'].str.replace(',', ';')

print("\nDataFrame after replacing ',' with ';':")
display(df.head())

DataFrame after replacing ',' with ';':

,Name,Sequence_protein,Sequence Length
0,tr|A0A1I9LPH3|A0A1I9LPH3_ARATH Uncharacterized...,REEVFSDVPLWLRQRPAFLVVLLLTEEEEEEDEEDLQVYIKWSHNP...,50
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854
2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPSLWQHEYLLSLGN...,565
3,tr|B3H6N5|B3H6N5_ARATH Uncharacterized protein...,MESIRSYIVASMDIDIPDQSVTEMNCLCLDLKLMGLG,37
4,tr|F4I2G0|F4I2G0_ARATH Ankyrin-repeat containi...,MGFTFTKIYTSSAPDLGITGLVKKAVFIVFLVCNSIPVLLSVIATM...,107

In [47]:
#add length of complete protein to df_IDR

# Assuming your second DataFrame is in a CSV file

#second_df = pd.read_csv('your_second_dataframe.csv')

# Merge the two DataFrames


#df_IDR[' FASTA header'] = df_IDR[' FASTA header'].str[1:]
merged_df = pd.merge(df_IDR, df, left_on=' FASTA header', right_on='Name', how='left')

# Drop the extra 'Name' column from the merge if you don't need it
#merged_df = merged_df.drop('Name', axis=1)

# Display the updated DataFrame
# display(merged_df.head())

# Drop the extra 'Name' column from the merge if you don't need it
merged_df = merged_df.drop('Name', axis=1)

# Display the updated DataFrame
display(merged_df.head())

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,...,kappa,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length
0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,1,66,66,23.80,55.49,0.404,0.535,7.015,...,0.212,0.076,0.197,0.121,0.076,0.303,0.212,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPN...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,306,525,220,47.99,115.33,0.419,0.569,5.882,...,0.176,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854
2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,1,34,34,16.55,40.86,0.455,0.568,6.505,...,0.297,0.029,0.265,0.059,0.118,0.382,0.147,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPS,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPSLWQHEYLLSLGN...,565
3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,1,292,292,54.52,122.24,0.427,0.552,6.358,...,0.179,0.164,0.123,0.058,0.027,0.384,0.240,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLIS...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660
4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,415,496,82,28.27,67.04,0.438,0.561,6.196,...,0.150,0.220,0.171,0.012,0.085,0.317,0.195,DNKNAYKPREGDSEHKEKPMQQIESLEGDDGADKSTHREKEKEAP...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660

In [76]:
print(df_IDR.iloc[2, 0])

sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; chloroplastic OS=Arabidopsis thaliana OX=3702 GN=TPS03 PE=1 SV=1_1_34

In [77]:
print(df_IDR.iloc[2, 1])

sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; chloroplastic OS=Arabidopsis thaliana OX=3702 GN=TPS03 PE=1 SV=1

In [38]:
print(df.iloc[2, 0])

sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3, chloroplastic OS=Arabidopsis thaliana OX=3702 GN=TPS03 PE=1 SV=1

In [39]:
df_IDR.iloc[1, 1][1:] == df.iloc[1, 0]

False

In [48]:

df_with_nan = merged_df[merged_df["Sequence_protein"].isna()]

print(f"\nRows where the Sequence_protein column has NaN values:")
display(df_with_nan)

Rows where the Sequence_protein column has NaN values:

Empty DataFrame
Columns: [IDR ID,  FASTA header,  IDR start,  IDR end,  IDR len,  Rg (A),  Re (A),  asphericity,  scaling_exponent,  prefactor,  FCR,  NCPR,  kappa,  fract_negative,  fract_positive,  fract_aro,  fract_pro,  fract_polar,  fract_ali,  sequence, Sequence_protein, Sequence Length]
Index: []

[0 rows x 22 columns]

In [58]:
display(merged_df)

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,1,66,66,23.80,55.49,0.404,0.535,7.015,...,0.076,0.197,0.121,0.076,0.303,0.212,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPN...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,N-terminal
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,306,525,220,47.99,115.33,0.419,0.569,5.882,...,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,middle
2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,1,34,34,16.55,40.86,0.455,0.568,6.505,...,0.029,0.265,0.059,0.118,0.382,0.147,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPS,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPSLWQHEYLLSLGN...,565,N-terminal
3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,1,292,292,54.52,122.24,0.427,0.552,6.358,...,0.164,0.123,0.058,0.027,0.384,0.240,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLIS...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,N-terminal
4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,415,496,82,28.27,67.04,0.438,0.561,6.196,...,0.220,0.171,0.012,0.085,0.317,0.195,DNKNAYKPREGDSEHKEKPMQQIESLEGDDGADKSTHREKEKEAP...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,middle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23611,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-...,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-...,332,540,209,44.63,104.93,0.410,0.544,6.643,...,0.144,0.115,0.067,0.086,0.373,0.211,KEKGKVPDKYRTNQTTERELSPTGLDSSPRDVLGGRGFYNNTQDV...,MDGYEATRIVLSRIQSLDPENASKIMGLLLLQDHGEKEMIRLAFGP...,540,C-terminal
23612,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,1,49,49,19.85,47.41,0.455,0.528,6.362,...,0.102,0.061,0.061,0.041,0.490,0.224,MNDLLSGSFKTSVADGSSPPHSHNIEMSKAKVSGGSCHGGNNLDT...,MNDLLSGSFKTSVADGSSPPHSHNIEMSKAKVSGGSCHGGNNLDTF...,341,N-terminal
23613,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,309,341,33,16.79,41.34,0.484,0.529,7.678,...,0.030,0.121,0.000,0.212,0.394,0.242,ESNGGGGGGAPRQATPVQAQPPPPPAVNRRLLR,MNDLLSGSFKTSVADGSSPPHSHNIEMSKAKVSGGSCHGGNNLDTF...,341,C-terminal
23614,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,1,115,115,29.11,68.63,0.406,0.536,6.129,...,0.017,0.026,0.104,0.035,0.548,0.261,MAKWFFTIFLVFALASALACGARNVPVGLSDQKNYLGYGGGYSGV...,MAKWFFTIFLVFALASALACGARNVPVGLSDQKNYLGYGGGYSGVG...,115,IDP
23615,sp|Q9XFB0|YAB2_ARATH Putative axial regulator ...,sp|Q9XFB0|YAB2_ARATH Putative axial regulator ...,1,115,115,32.47,79.28,0.407,0.541,6.625,...,0.070,0.104,0.043,0.078,0.374,0.278,MSVDFSSERVCYVHCSFCTTILAVSVPYASLFTLVTVRCGHCTNL...,MSVDFSSERVCYVHCSFCTTILAVSVPYASLFTLVTVRCGHCTNLL...,184,N-terminal

In [95]:
merged_df.to_csv('/home/wenyuantong/Desktop/data/arabi_IDR_location.csv', index=True)

In [8]:

import numpy as np

In [3]:
import pandas as pd

# Replace 'your_file.csv' with the actual path to your CSV file
csv_file_path = '/home/wenyuantong/Desktop/data/arabi_IDR_location.csv'

try:
    # Read the CSV file into a DataFrame
    merged_df = pd.read_csv(csv_file_path)

    print(f"Successfully loaded '{csv_file_path}' into a DataFrame.")
    # Display the first 5 rows of the DataFrame
    display(merged_df.head())

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Successfully loaded '/home/wenyuantong/Desktop/data/arabi_IDR_location.csv' into a DataFrame.

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,1,66,66,23.80,55.49,0.404,0.535,...,0.076,0.197,0.121,0.076,0.303,0.212,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPN...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,N-terminal
1,1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,306,525,220,47.99,115.33,0.419,0.569,...,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,middle
2,2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,1,34,34,16.55,40.86,0.455,0.568,...,0.029,0.265,0.059,0.118,0.382,0.147,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPS,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPSLWQHEYLLSLGN...,565,N-terminal
3,3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,1,292,292,54.52,122.24,0.427,0.552,...,0.164,0.123,0.058,0.027,0.384,0.240,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLIS...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,N-terminal
4,4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,415,496,82,28.27,67.04,0.438,0.561,...,0.220,0.171,0.012,0.085,0.317,0.195,DNKNAYKPREGDSEHKEKPMQQIESLEGDDGADKSTHREKEKEAP...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,middle

In [13]:

# Define the conditions
#conditions = [
#    (merged_df[' IDR start'] == 1) & (merged_df[' IDR end'] < merged_df['Sequence Length']),
#    (merged_df[' IDR start'] == 1) & (merged_df[' IDR end'] == merged_df['Sequence Length']),
#    (merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] == merged_df['Sequence Length']),
#    (merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] < merged_df['Sequence Length'])
#]



# Define the conditions
conditions = [
    # First condition: 'IDR start' between 1 and 20 (inclusive) and 'IDR end' less than 'sequence length'
    (merged_df[' IDR start'] >= 1) & (merged_df[' IDR start'] <= 20) & (merged_df[' IDR end'] < merged_df['Sequence Length']),
    # Second condition: 'IDR start' is 1 and 'IDR end' is equal to 'sequence length'
    (merged_df[' IDR start'] == 1) & (merged_df[' IDR end'] == merged_df['Sequence Length']),
    # Third condition: 'IDR start' is greater than 1 and 'IDR end' is between 'sequence length' and 20 before (inclusive)
    (merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] <= merged_df['Sequence Length']) & (merged_df[' IDR end'] >= merged_df['Sequence Length'] - 20),
    # Fourth condition: 'IDR start' is greater than 1 and 'IDR end' is less than 'sequence length' (and not covered by the third condition)
    #(merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] < merged_df['Sequence Length']) & (merged_df[' IDR end'] < merged_df['Sequence Length'] - 20)
    (merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] < merged_df['Sequence Length']) &
    ~((merged_df[' IDR start'] >= 1) & (merged_df[' IDR start'] <= 20)) & # Exclude first condition's start range
    ~((merged_df[' IDR end'] <= merged_df['Sequence Length']) & (merged_df[' IDR end'] >= merged_df['Sequence Length'] - 20)) # Exclude third condition's end range
]

# Define the corresponding values for the new 'location' column
values = ['N-terminal', 'IDP', 'C-terminal', 'Middle']

# Create the new 'location' column using np.select
merged_df['location'] = np.select(conditions, values, default='unknown') # 'unknown' for cases that don't match any condition

print("\nDataFrame with 'location' column:")
display(merged_df.head())

DataFrame with 'location' column:

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,1,66,66,23.80,55.49,0.404,0.535,...,0.076,0.197,0.121,0.076,0.303,0.212,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPN...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,N-terminal
1,1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,306,525,220,47.99,115.33,0.419,0.569,...,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,Middle
2,2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,1,34,34,16.55,40.86,0.455,0.568,...,0.029,0.265,0.059,0.118,0.382,0.147,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPS,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPSLWQHEYLLSLGN...,565,N-terminal
3,3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,1,292,292,54.52,122.24,0.427,0.552,...,0.164,0.123,0.058,0.027,0.384,0.240,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLIS...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,N-terminal
4,4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,415,496,82,28.27,67.04,0.438,0.561,...,0.220,0.171,0.012,0.085,0.317,0.195,DNKNAYKPREGDSEHKEKPMQQIESLEGDDGADKSTHREKEKEAP...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,Middle

In [15]:
# Filter the DataFrame for rows where 'location' is 'unknown'
unknown_location_df = merged_df[merged_df['location'] == 'Middle']

print("\nDataFrame with only 'unknown' locations:")
display(unknown_location_df)

DataFrame with only 'unknown' locations:

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
1,1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,306,525,220,47.99,115.33,0.419,0.569,...,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,Middle
4,4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,415,496,82,28.27,67.04,0.438,0.561,...,0.220,0.171,0.012,0.085,0.317,0.195,DNKNAYKPREGDSEHKEKPMQQIESLEGDDGADKSTHREKEKEAP...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,Middle
5,5,sp|F4IB81|LYK3_ARATH LysM domain receptor-like...,sp|F4IB81|LYK3_ARATH LysM domain receptor-like...,191,325,135,33.70,81.69,0.402,0.539,...,0.089,0.074,0.067,0.067,0.370,0.281,VPGEPYETSKINPPAPSPAPASSLANGNISDDQVNHTAKSGSHVP...,MNLTFYIFFLSLLPSFSSSKPMNCSDTTRLCSSFLAFKPNQNQSFS...,651,Middle
6,6,sp|F4IRU3|MYO12_ARATH Myosin-12 OS=Arabidopsis...,sp|F4IRU3|MYO12_ARATH Myosin-12 OS=Arabidopsis...,1071,1134,64,24.30,57.61,0.437,0.557,...,0.172,0.156,0.016,0.062,0.344,0.250,ILESENETLRRQTESAEKTMPPARVFASEKNLENEHQTKEIQATK...,MGTPVNITLGSHVWVEDPELAWISGEVTEIKGTNAKIVTANGKTVV...,1556,Middle
7,7,sp|F4IRU3|MYO12_ARATH Myosin-12 OS=Arabidopsis...,sp|F4IRU3|MYO12_ARATH Myosin-12 OS=Arabidopsis...,1221,1270,50,19.58,46.01,0.411,0.533,...,0.040,0.080,0.040,0.040,0.560,0.240,SNTNNAASRRNRSSHATLFGRLVQGMQPSSVGLETSSGYSGMAGI...,MGTPVNITLGSHVWVEDPELAWISGEVTEIKGTNAKIVTANGKTVV...,1556,Middle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23596,23596,sp|Q944Q0|WNK8_ARATH Serine/threonine-protein ...,sp|Q944Q0|WNK8_ARATH Serine/threonine-protein ...,425,509,85,26.12,60.90,0.414,0.531,...,0.153,0.059,0.071,0.024,0.435,0.247,RTSSHHNQNSPRLTHEDHEAANQQTVNSKDEEAAGQSMKSDISAD...,MASGSGFLGQISSMEEADFAEKDPSGRYIRYDDVLGRGAFKTVYKA...,563,Middle
23599,23599,sp|Q9ATB4|TAD2B_ARATH Transcriptional adapter ...,sp|Q9ATB4|TAD2B_ARATH Transcriptional adapter ...,181,246,66,23.60,56.31,0.415,0.533,...,0.197,0.167,0.106,0.076,0.303,0.152,KKAEQNMKEEYPFSPPKVKVEDTQKESFVDRSFGGKKPVSTSVNN...,MGRSRGNFQNFEDPTQRTRKKKNAANVENFESTSLVPGAEGGGKYN...,487,Middle
23600,23600,sp|Q9ATB4|TAD2B_ARATH Transcriptional adapter ...,sp|Q9ATB4|TAD2B_ARATH Transcriptional adapter ...,365,416,52,20.06,47.53,0.428,0.529,...,0.135,0.154,0.077,0.038,0.385,0.212,YLGRKRKRENEEGMNRGKESGQFGQIAGEMGSRPPVQASSSYVND...,MGRSRGNFQNFEDPTQRTRKKKNAANVENFESTSLVPGAEGGGKYN...,487,Middle
23602,23602,tr|Q9C6K4|Q9C6K4_ARATH Transcription factor OS...,tr|Q9C6K4|Q9C6K4_ARATH Transcription factor OS...,209,305,97,28.42,68.61,0.409,0.520,...,0.237,0.113,0.021,0.062,0.351,0.206,NRLHLPHDPAVQRSLHLITLGSRDDHDNDEHGKHQNEDLDDDDDY...,MEGNCSQGRFDSQVSSMRDLRPNAINQNQKQHHPNSRQDSGFNNTM...,385,Middle
23610,23610,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-...,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-...,65,223,159,35.78,84.65,0.392,0.505,...,0.094,0.094,0.082,0.057,0.421,0.220,NCSRSPWSHQDELISPKNNRGSSLNPASLPFYANGGRSSRDLTND...,MDGYEATRIVLSRIQSLDPENASKIMGLLLLQDHGEKEMIRLAFGP...,540,Middle

In [82]:
#Index(['IDR ID', ' FASTA header', ' IDR start', ' IDR end', ' IDR len',
      # ' Rg (A)', ' Re (A)', ' asphericity', ' scaling_exponent', ' prefactor',
      # ' FCR', ' NCPR', ' kappa', ' fract_negative', ' fract_positive',
      # ' fract_aro', ' fract_pro', ' fract_polar', ' fract_ali', ' sequence'],
     # dtype='object')

# Specify the columns you want to include in the sub-DataFrame
selected_columns = ['IDR ID', ' Rg (A)', ' Re (A)', ' asphericity', ' scaling_exponent']

# Create the sub-DataFrame by selecting the specified columns
sub_df = merged_df[selected_columns]

print(f"\nSub-DataFrame with selected columns: {selected_columns}")
display(sub_df)

Sub-DataFrame with selected columns: ['IDR ID', ' Rg (A)', ' Re (A)', ' asphericity', ' scaling_exponent']

,IDR ID,Rg (A),Re (A),asphericity,scaling_exponent
0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,23.80,55.49,0.404,0.535
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,47.99,115.33,0.419,0.569
2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,16.55,40.86,0.455,0.568
3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,54.52,122.24,0.427,0.552
4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,28.27,67.04,0.438,0.561
...,...,...,...,...,...
23611,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-...,44.63,104.93,0.410,0.544
23612,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,19.85,47.41,0.455,0.528
23613,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,16.79,41.34,0.484,0.529
23614,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,29.11,68.63,0.406,0.536
23615,sp|Q9XFB0|YAB2_ARATH Putative axial regulator ...,32.47,79.28,0.407,0.541

In [83]:
# Specify the column to normalize
column_to_normalize = ' Rg (A)'

# Calculate the minimum and maximum values of the column
min_value = sub_df[column_to_normalize].min()
max_value = sub_df[column_to_normalize].max()

# Apply min-max scaling
sub_df['Normalized Rg (A)'] = (sub_df[column_to_normalize] - min_value) / (max_value - min_value)

print(f"\nDataFrame after normalizing '{column_to_normalize}':")
display(sub_df)

DataFrame after normalizing ' Rg (A)':

/tmp/ipykernel_327510/3999536360.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df['Normalized Rg (A)'] = (sub_df[column_to_normalize] - min_value) / (max_value - min_value)

,IDR ID,Rg (A),Re (A),asphericity,scaling_exponent,Normalized Rg (A)
0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,23.80,55.49,0.404,0.535,0.042808
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,47.99,115.33,0.419,0.569,0.144631
2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,16.55,40.86,0.455,0.568,0.012291
3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,54.52,122.24,0.427,0.552,0.172118
4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,28.27,67.04,0.438,0.561,0.061624
...,...,...,...,...,...,...
23611,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-...,44.63,104.93,0.410,0.544,0.130488
23612,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,19.85,47.41,0.455,0.528,0.026182
23613,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,16.79,41.34,0.484,0.529,0.013301
23614,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,29.11,68.63,0.406,0.536,0.065160
23615,sp|Q9XFB0|YAB2_ARATH Putative axial regulator ...,32.47,79.28,0.407,0.541,0.079303

In [84]:
# Specify the column to normalize
column_to_normalize = ' Re (A)'

# Calculate the minimum and maximum values of the column
min_value = sub_df[column_to_normalize].min()
max_value = sub_df[column_to_normalize].max()

# Apply min-max scaling
sub_df['Normalized Re (A)'] = (sub_df[column_to_normalize] - min_value) / (max_value - min_value)

print(f"\nDataFrame after normalizing '{column_to_normalize}':")
display(sub_df)

DataFrame after normalizing ' Re (A)':

/tmp/ipykernel_327510/3755703316.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df['Normalized Re (A)'] = (sub_df[column_to_normalize] - min_value) / (max_value - min_value)

,IDR ID,Rg (A),Re (A),asphericity,scaling_exponent,Normalized Rg (A),Normalized Re (A)
0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,23.80,55.49,0.404,0.535,0.042808,0.051648
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,47.99,115.33,0.419,0.569,0.144631,0.169385
2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,16.55,40.86,0.455,0.568,0.012291,0.022863
3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,54.52,122.24,0.427,0.552,0.172118,0.182981
4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,28.27,67.04,0.438,0.561,0.061624,0.074373
...,...,...,...,...,...,...,...
23611,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-...,44.63,104.93,0.410,0.544,0.130488,0.148923
23612,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,19.85,47.41,0.455,0.528,0.026182,0.035750
23613,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,16.79,41.34,0.484,0.529,0.013301,0.023807
23614,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,29.11,68.63,0.406,0.536,0.065160,0.077501
23615,sp|Q9XFB0|YAB2_ARATH Putative axial regulator ...,32.47,79.28,0.407,0.541,0.079303,0.098455

In [92]:
display(sub_df)
#sub_df.to_csv('filename.csv', index=False)

,asphericity,scaling_exponent,Normalized Rg (A),Normalized Re (A)
IDR ID,,,,
tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride lipase OS=Arabidopsis thaliana OX=3702 GN=HIL1 PE=1 SV=1_1_66,0.404,0.535,0.042808,0.051648
tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride lipase OS=Arabidopsis thaliana OX=3702 GN=HIL1 PE=1 SV=1_306_525,0.419,0.569,0.144631,0.169385
sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; chloroplastic OS=Arabidopsis thaliana OX=3702 GN=TPS03 PE=1 SV=1_1_34,0.455,0.568,0.012291,0.022863
sp|F4I316|SUN3_ARATH SUN domain-containing protein 3 OS=Arabidopsis thaliana OX=3702 GN=SUN3 PE=1 SV=1_1_292,0.427,0.552,0.172118,0.182981
sp|F4I316|SUN3_ARATH SUN domain-containing protein 3 OS=Arabidopsis thaliana OX=3702 GN=SUN3 PE=1 SV=1_415_496,0.438,0.561,0.061624,0.074373
...,...,...,...,...
sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-containing protein 46 OS=Arabidopsis thaliana OX=3702 GN=At3g51950 PE=1 SV=1_332_540,0.410,0.544,0.130488,0.148923
sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidopsis thaliana OX=3702 GN=SYP122 PE=1 SV=1_1_49,0.455,0.528,0.026182,0.035750
sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidopsis thaliana OX=3702 GN=SYP122 PE=1 SV=1_309_341,0.484,0.529,0.013301,0.023807
tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein like OS=Arabidopsis thaliana OX=3702 GN=At4g29030 PE=2 SV=1_1_115,0.406,0.536,0.065160,0.077501
sp|Q9XFB0|YAB2_ARATH Putative axial regulator YABBY 2 OS=Arabidopsis thaliana OX=3702 GN=YAB2 PE=1 SV=1_1_115,0.407,0.541,0.079303,0.098455

In [87]:
sub_df.set_index(sub_df.columns[0], inplace=True)

In [91]:
sub_df.drop(columns=[' Re (A)'], inplace=True)

/tmp/ipykernel_327510/289107046.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df.drop(columns=[' Re (A)'], inplace=True)

In [94]:
sub_df.to_csv('/home/wenyuantong/Desktop/data/Albatross_minmax_norm_arabi.csv', index=True)

In [75]:
sc.tl.pca(adata, svd_solver='arpack')

In [78]:
sc.pp.neighbors(adata, n_neighbors=10, use_rep='X_pca')

/home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm