In [1]:
import numpy as np
import matplotlib

import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

import pandas as pd

import re

In [30]:
# load TSV file
csv_file_path = '/home/wenyuantong/Desktop/data/IDR_arabi_domain.tsv'

try:
    # Read the CSV file into a DataFrame
    dom2_df = pd.read_csv(csv_file_path, sep="\t", header=None)

    print(f"Successfully loaded '{csv_file_path}' into a DataFrame.")
    # Display the first 5 rows of the DataFrame
    display(dom2_df.head())

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Successfully loaded '/home/wenyuantong/Desktop/data/IDR_arabi_domain.tsv' into a DataFrame.

            0    1    2           3
0  A0A1P8B415    1   66  N-terminal
1  A0A1P8B415  306  525      middle
2      A4FVP2    1   34  N-terminal
3      F4I316    1  292  N-terminal
4      F4I316  415  496      middle

In [31]:
# load second TSV file
csv_file_path = '/home/wenyuantong/Desktop/data/IDR_psytec_domain.tsv'

try:
    # Read the CSV file into a DataFrame
    dom1_df = pd.read_csv(csv_file_path, sep="\t", header=None)

    print(f"Successfully loaded '{csv_file_path}' into a DataFrame.")
    # Display the first 5 rows of the DataFrame
    display(dom1_df.head())

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Successfully loaded '/home/wenyuantong/Desktop/data/IDR_psytec_domain.tsv' into a DataFrame.

         0    1    2           3
0  HopX1a     1   88  N-terminal
1  HopX1a   200  247      Middle
2  HopX1a   298  380  C-terminal
3  HopX1c     1   87  N-terminal
4  HopX1c   212  267      Middle

In [32]:
# Define the word to search for
search_word = 'Q9LD45'

# Filter the DataFrame
df2 = dom2_df[dom2_df[0].str.contains(search_word, case=False, na=False)]

print(f"\nDataFrame filtered for rows containing '{search_word}':")
display(df2)

DataFrame filtered for rows containing 'Q9LD45':

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [28]:
#dom_all = df1
dom1_df = pd.concat([dom1_df, df2], ignore_index=True)

print("DataFrame after adding a new row:")
display(dom1_df)

DataFrame after adding a new row:

           0     1     2           3
0    HopX1a      1    88  N-terminal
1    HopX1a    200   247      Middle
2    HopX1a    298   380  C-terminal
3    HopX1c      1    87  N-terminal
4    HopX1c    212   267      Middle
..       ...   ...   ...         ...
591  HopZ5b    283   346  C-terminal
592  AvrB1b      1    31  N-terminal
593   Q5S2C4     1    60  N-terminal
594   Q5S2C4   767   805      middle
595   Q5S2C4  1288  1425  C-terminal

[596 rows x 4 columns]

In [24]:
display(dom1_df)

           0    1     2           3
0    HopX1a     1    88  N-terminal
1    HopX1a   200   247      Middle
2    HopX1a   298   380  C-terminal
3    HopX1c     1    87  N-terminal
4    HopX1c   212   267      Middle
..       ...  ...   ...         ...
591  HopZ5b   283   346  C-terminal
592  AvrB1b     1    31  N-terminal
593   P93002  557   593  C-terminal
594   F4KG14    1    41  N-terminal
595   F4KG14  949  1022      middle

[596 rows x 4 columns]

In [13]:
#df = dom1_df.iloc[:-2]

In [23]:
#display(df)

In [29]:
dom1_df.to_csv("/home/wenyuantong/Desktop/data/HEM1_domain_all.tsv", sep='\t', index=False)