In [2]:
import pandas as pd


file_path = 'RIN4_domain.tsv'

try:
    df_rin4 = pd.read_csv(file_path, sep='\t', header = None)
    print("RIN4_domain.tsv loaded successfully!")
    display(df_rin4.head())
except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please check the path and try again.")
except Exception as e:
    print(f"An error occurred while reading the file: {e}")

RIN4_domain.tsv loaded successfully!

           0  1    2           3
0          0  1    2           3
1  AvrRpm1a   1  228  N-terminal
2  AvrRpm1h   1  228  N-terminal
3  AvrRpm1d   1  100  N-terminal
4  AvrRpm1e   1   55  N-terminal

In [10]:
display(df_rin4.tail())

          0    1     2    3
995  Q8L3P4  338   654  IDR
996  Q8RWG0  968  1007  IDR
997  Q8LBB5    1    57  IDR
998  Q8RX56   85   257  IDR
999  O81037    1   191  IDR

In [11]:
# Define the minimum and maximum allowed lengths for segments
MIN_LENGTH = 30
MAX_LENGTH = 80

# List to store the new, processed rows
processed_rows = []

# Iterate through each row of the original DataFrame
for index, row in df_rin4.iterrows():
    protein_name = row[0]
    start_pos = row[1]
    end_pos = row[2]
    domain_type = row[3]

    # Calculate the current length of the entry
    current_length = end_pos - start_pos + 1

    # If the entry is too long, split it into segments
    if current_length > MAX_LENGTH:
        segment_start = start_pos
        segment_count = 1
        while segment_start <= end_pos:
            # Determine the end position for the current segment, ensuring it doesn't exceed MAX_LENGTH or the original end_pos
            segment_end = min(segment_start + MAX_LENGTH - 1, end_pos)
            segment_length = segment_end - segment_start + 1

            # Only add the segment if its length is within the desired range
            if segment_length >= MIN_LENGTH:
                processed_rows.append([protein_name, segment_start, segment_end, f"{domain_type}_{segment_count}"])

            # Move to the start of the next segment
            segment_start = segment_end + 1
            segment_count += 1
    # If the entry is within the allowed length range, add it as is (with a '_1' suffix as per example)
    elif current_length >= MIN_LENGTH and current_length <= MAX_LENGTH:
        processed_rows.append([protein_name, start_pos, end_pos, f"{domain_type}_1"])
    # Entries shorter than MIN_LENGTH are implicitly dropped due to the conditions above

# Create the new DataFrame from the processed rows
df_processed = pd.DataFrame(processed_rows, columns=df_rin4.columns)

print("New DataFrame with entries segmented to be between 30 and 80 in length:")
display(df_processed)

New DataFrame with entries segmented to be between 30 and 80 in length:

             0     1     2      3
0      HopD1d      1    47  IDR_1
1      HopZ1m    304   367  IDR_1
2     HopAF1n      1    50  IDR_1
3      AvrE1x   1054  1133  IDR_1
4      HopW1m    670   749  IDR_1
...        ...   ...   ...    ...
1586    Q8RX56    85   164  IDR_1
1587    Q8RX56   165   244  IDR_2
1588    O81037     1    80  IDR_1
1589    O81037    81   160  IDR_2
1590    O81037   161   191  IDR_3

[1591 rows x 4 columns]

In [12]:
display(df_processed.tail())

           0    1    2      3
1586  Q8RX56   85  164  IDR_1
1587  Q8RX56  165  244  IDR_2
1588  O81037    1   80  IDR_1
1589  O81037   81  160  IDR_2
1590  O81037  161  191  IDR_3

In [ ]:
#The new DataFrame `df_processed` now contains entries that are all within the 30 to 80 length range
#Longer original entries have been split, and their `Domain_Type` column has been suffixed with `_1`, `_2`, etc
#Entries shorter than 30 have been excluded.

In [1]:
output_file_path = 'IDR_arabi_effector_domain_cut.tsv'

try:
    df_processed.to_csv(output_file_path, sep='\t', index=False)
    print(f"DataFrame successfully saved to '{output_file_path}'")
except Exception as e:
    print(f"An error occurred while saving the file: {e}")

An error occurred while saving the file: name 'df_processed' is not defined

In [3]:
import pandas as pd

# Filter df_rin4 to include rows where column 0 is 'Q8GYN5' or starts with 'AvrB1'
df_filtered = df_rin4[
    (df_rin4[0] == 'Q8GYN5') |
    (df_rin4[0].astype(str).str.startswith('AvrB1'))
].copy()

print("Sub-DataFrame containing 'Q8GYN5' and 'AvrB1*' entries:")
display(df_filtered)

Sub-DataFrame containing 'Q8GYN5' and 'AvrB1*' entries:

          0  1    2           3
16  AvrB1b   1   31  N-terminal
20   Q8GYN5  1  211         IDP