In [12]:

import pandas as pd


try:
    df = pd.read_csv('~/Downloads/IDRome_all.csv')
    display(df)
    filtered_df = df[df.iloc[:, 4] > 30]
    print("Filtered data (lengths > 30):")
    #display(filtered_df)
except FileNotFoundError:
    print("Error: 'your_file.csv' not found. Please replace with the correct file path.")
except Exception as e:
    print(f"An error occurred: {e}")

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,FCR,NCPR,kappa,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence
0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride l...,1,66,66,23.80,55.49,0.404,0.535,7.015,0.273,0.121,0.212,0.076,0.197,0.121,0.076,0.303,0.212,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPN...
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride l...,306,525,220,47.99,115.33,0.419,0.569,5.882,0.286,-0.095,0.176,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...
2,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride l...,841,854,14,9.22,22.98,0.498,0.512,5.781,0.214,-0.071,0.430,0.143,0.071,0.000,0.000,0.571,0.214,KGVESTTIQSVGES
3,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; c...,1,34,34,16.55,40.86,0.455,0.568,6.505,0.294,0.235,0.297,0.029,0.265,0.059,0.118,0.382,0.147,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPS
4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pr...,1,292,292,54.52,122.24,0.427,0.552,6.358,0.288,-0.041,0.179,0.164,0.123,0.058,0.027,0.384,0.240,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLIS...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34906,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein l...,1,115,115,29.11,68.63,0.406,0.536,6.129,0.043,0.009,0.331,0.017,0.026,0.104,0.035,0.548,0.261,MAKWFFTIFLVFALASALACGARNVPVGLSDQKNYLGYGGGYSGV...
34907,sp|Q9SZT0|P4H11_ARATH Probable prolyl 4-hydrox...,sp|Q9SZT0|P4H11_ARATH Probable prolyl 4-hydro...,135,150,16,9.32,24.36,0.473,0.520,6.139,0.188,-0.062,0.837,0.125,0.062,0.000,0.000,0.625,0.188,NALTGLGEESSSRTSS
34908,sp|Q9SZT0|P4H11_ARATH Probable prolyl 4-hydrox...,sp|Q9SZT0|P4H11_ARATH Probable prolyl 4-hydro...,251,272,22,12.68,29.74,0.460,0.576,5.474,0.273,0.091,0.388,0.091,0.182,0.045,0.091,0.409,0.136,PDGSRDPSSKHGKRHCLSLNLF
34909,sp|Q9XFB0|YAB2_ARATH Putative axial regulator ...,sp|Q9XFB0|YAB2_ARATH Putative axial regulator...,1,115,115,32.47,79.28,0.407,0.541,6.625,0.174,0.035,0.134,0.070,0.104,0.043,0.078,0.374,0.278,MSVDFSSERVCYVHCSFCTTILAVSVPYASLFTLVTVRCGHCTNL...
34910,sp|Q9XFB0|YAB2_ARATH Putative axial regulator ...,sp|Q9XFB0|YAB2_ARATH Putative axial regulator...,158,184,27,13.52,32.14,0.377,0.600,6.143,0.259,0.111,0.298,0.074,0.185,0.111,0.000,0.444,0.185,FGLKLDGNKKGKQLDQSVAGQKSNGYY

Filtered data (lengths > 30):

In [3]:
# Save the filtered DataFrame to a new CSV file
try:
    filtered_df.to_csv('~/Desktop/data/filtered_IDR_Arabi.csv', index=False)
    print("Filtered data saved to 'filtered_lengths.csv'")
except NameError:
    print("Error: 'filtered_df' not found. Please run the previous cell to filter the data first.")
except Exception as e:
    print(f"An error occurred while saving the file: {e}")

Filtered data saved to 'filtered_lengths.csv'

In [4]:
display(filtered_df.columns)

Index(['IDR ID', ' FASTA header', ' IDR start', ' IDR end', ' IDR len',
       ' Rg (A)', ' Re (A)', ' asphericity', ' scaling_exponent', ' prefactor',
       ' FCR', ' NCPR', ' kappa', ' fract_negative', ' fract_positive',
       ' fract_aro', ' fract_pro', ' fract_polar', ' fract_ali', ' sequence'],
      dtype='object')

In [7]:
#filtered_df[' sequence'] = filtered_df[' sequence'].str.replace(' ', '', regex=False)

#print(f"\nDataFrame after removing '{'<unknown description>'}':")
display(filtered_df)

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,FCR,NCPR,kappa,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence
0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride l...,1,66,66,23.80,55.49,0.404,0.535,7.015,0.273,0.121,0.212,0.076,0.197,0.121,0.076,0.303,0.212,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPN...
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride l...,306,525,220,47.99,115.33,0.419,0.569,5.882,0.286,-0.095,0.176,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...
3,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; c...,1,34,34,16.55,40.86,0.455,0.568,6.505,0.294,0.235,0.297,0.029,0.265,0.059,0.118,0.382,0.147,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPS
4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pr...,1,292,292,54.52,122.24,0.427,0.552,6.358,0.288,-0.041,0.179,0.164,0.123,0.058,0.027,0.384,0.240,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLIS...
5,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pr...,415,496,82,28.27,67.04,0.438,0.561,6.196,0.390,-0.049,0.150,0.220,0.171,0.012,0.085,0.317,0.195,DNKNAYKPREGDSEHKEKPMQQIESLEGDDGADKSTHREKEKEAP...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34902,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-...,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain...,332,540,209,44.63,104.93,0.410,0.544,6.643,0.258,-0.029,0.182,0.144,0.115,0.067,0.086,0.373,0.211,KEKGKVPDKYRTNQTTERELSPTGLDSSPRDVLGGRGFYNNTQDV...
34903,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabido...,1,49,49,19.85,47.41,0.455,0.528,6.362,0.163,-0.041,0.308,0.102,0.061,0.061,0.041,0.490,0.224,MNDLLSGSFKTSVADGSSPPHSHNIEMSKAKVSGGSCHGGNNLDT...
34905,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabido...,309,341,33,16.79,41.34,0.484,0.529,7.678,0.152,0.091,0.540,0.030,0.121,0.000,0.212,0.394,0.242,ESNGGGGGGAPRQATPVQAQPPPPPAVNRRLLR
34906,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein l...,1,115,115,29.11,68.63,0.406,0.536,6.129,0.043,0.009,0.331,0.017,0.026,0.104,0.035,0.548,0.261,MAKWFFTIFLVFALASALACGARNVPVGLSDQKNYLGYGGGYSGV...
34909,sp|Q9XFB0|YAB2_ARATH Putative axial regulator ...,sp|Q9XFB0|YAB2_ARATH Putative axial regulator...,1,115,115,32.47,79.28,0.407,0.541,6.625,0.174,0.035,0.134,0.070,0.104,0.043,0.078,0.374,0.278,MSVDFSSERVCYVHCSFCTTILAVSVPYASLFTLVTVRCGHCTNL...

In [5]:
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio import SeqIO

In [6]:
records = []
for index, row in filtered_df.iterrows():
    try:
        sequence_id = str(row['IDR ID'])
        protein_sequence = str(row[' sequence'])
        #type_protein =str(row['FinalType'])

        # Create a SeqRecord object for each protein sequence
        record = SeqRecord(
            Seq(protein_sequence),
            id=sequence_id,
            description=''# You can add a description if available in another column
        )
        records.append(record)
    except KeyError as e:
        print(f"Error: Missing column '{e}' in the DataFrame. Please check column names.")
        #return
    except Exception as e:
        print(f"Error processing row {index}: {e}")
        #continue

In [8]:
print(records[88])

ID: tr|A8MRC1|A8MRC1_ARATH Asparagine synthase family protein OS=Arabidopsis thaliana OX=3702 GN=At2g03667 PE=1 SV=2_571_610
Name: <unknown name>
Number of features: 0
Seq(' KRAIQFGSRIARESNRKNFGSNRAANQASAGSVRFLAPSH')

In [10]:
try:
    with open('/home/wenyuantong/Desktop/data/filtered_IDR_Arabi.fasta', "w") as output_handle:
        SeqIO.write(records, output_handle, "fasta")
    print(f"FASTA file successfully created at {'/home/wenyuantong/Desktop/data/filtered_IDR_Arabi.fasta'}")
except Exception as e:
    print(f"Error writing FASTA file: {e}")

FASTA file successfully created at /home/wenyuantong/Desktop/data/filtered_IDR_Arabi.fasta

In [11]:
display(filtered_df)

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,FCR,NCPR,kappa,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence
0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride l...,1,66,66,23.80,55.49,0.404,0.535,7.015,0.273,0.121,0.212,0.076,0.197,0.121,0.076,0.303,0.212,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPN...
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride l...,306,525,220,47.99,115.33,0.419,0.569,5.882,0.286,-0.095,0.176,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...
3,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; c...,1,34,34,16.55,40.86,0.455,0.568,6.505,0.294,0.235,0.297,0.029,0.265,0.059,0.118,0.382,0.147,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPS
4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pr...,1,292,292,54.52,122.24,0.427,0.552,6.358,0.288,-0.041,0.179,0.164,0.123,0.058,0.027,0.384,0.240,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLIS...
5,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pr...,415,496,82,28.27,67.04,0.438,0.561,6.196,0.390,-0.049,0.150,0.220,0.171,0.012,0.085,0.317,0.195,DNKNAYKPREGDSEHKEKPMQQIESLEGDDGADKSTHREKEKEAP...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34902,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-...,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain...,332,540,209,44.63,104.93,0.410,0.544,6.643,0.258,-0.029,0.182,0.144,0.115,0.067,0.086,0.373,0.211,KEKGKVPDKYRTNQTTERELSPTGLDSSPRDVLGGRGFYNNTQDV...
34903,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabido...,1,49,49,19.85,47.41,0.455,0.528,6.362,0.163,-0.041,0.308,0.102,0.061,0.061,0.041,0.490,0.224,MNDLLSGSFKTSVADGSSPPHSHNIEMSKAKVSGGSCHGGNNLDT...
34905,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabido...,309,341,33,16.79,41.34,0.484,0.529,7.678,0.152,0.091,0.540,0.030,0.121,0.000,0.212,0.394,0.242,ESNGGGGGGAPRQATPVQAQPPPPPAVNRRLLR
34906,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein l...,1,115,115,29.11,68.63,0.406,0.536,6.129,0.043,0.009,0.331,0.017,0.026,0.104,0.035,0.548,0.261,MAKWFFTIFLVFALASALACGARNVPVGLSDQKNYLGYGGGYSGV...
34909,sp|Q9XFB0|YAB2_ARATH Putative axial regulator ...,sp|Q9XFB0|YAB2_ARATH Putative axial regulator...,1,115,115,32.47,79.28,0.407,0.541,6.625,0.174,0.035,0.134,0.070,0.104,0.043,0.078,0.374,0.278,MSVDFSSERVCYVHCSFCTTILAVSVPYASLFTLVTVRCGHCTNL...

In [9]:
#find how many proteins are unique (ex. there can be more than 1 IDR per protein.

# Find the number of unique values in 'col1'
unique_count_col1 = filtered_df[' FASTA header'].nunique()
print(f"\nNumber of unique values in 'col1': {unique_count_col1}")

Number of unique values in 'col1': 17501