In [1]:
import pandas as pd

import numpy as np

In [2]:


csv_file_path = '/home/wenyuantong/Desktop/data/arabi_IDR_location.csv'

try:
    # Read the CSV file into a DataFrame
    merged_df = pd.read_csv(csv_file_path)

    print(f"Successfully loaded '{csv_file_path}' into a DataFrame.")
    # Display the first 5 rows of the DataFrame
    display(merged_df.head())

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Successfully loaded '/home/wenyuantong/Desktop/data/arabi_IDR_location.csv' into a DataFrame.

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,1,66,66,23.80,55.49,0.404,0.535,...,0.076,0.197,0.121,0.076,0.303,0.212,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPN...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,N-terminal
1,1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,306,525,220,47.99,115.33,0.419,0.569,...,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,middle
2,2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,1,34,34,16.55,40.86,0.455,0.568,...,0.029,0.265,0.059,0.118,0.382,0.147,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPS,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPSLWQHEYLLSLGN...,565,N-terminal
3,3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,1,292,292,54.52,122.24,0.427,0.552,...,0.164,0.123,0.058,0.027,0.384,0.240,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLIS...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,N-terminal
4,4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,415,496,82,28.27,67.04,0.438,0.561,...,0.220,0.171,0.012,0.085,0.317,0.195,DNKNAYKPREGDSEHKEKPMQQIESLEGDDGADKSTHREKEKEAP...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,middle

In [3]:
print(merged_df.columns.tolist())

['Unnamed: 0', 'IDR ID', ' FASTA header', ' IDR start', ' IDR end', ' IDR len', ' Rg (A)', ' Re (A)', ' asphericity', ' scaling_exponent', ' prefactor', ' FCR', ' NCPR', ' kappa', ' fract_negative', ' fract_positive', ' fract_aro', ' fract_pro', ' fract_polar', ' fract_ali', ' sequence', 'Sequence_protein', 'Sequence Length', 'location']

In [4]:
# Specify the columns you want to include in the sub-DataFrame
#ProteinID,RegionID,Start,Stop
#DDX3X,N-IDR,0,142
#protein_x,region3,24,72
selected_columns = [' FASTA header', 'location', ' IDR start',' IDR end' ]

# Create the sub-DataFrame by selecting the specified columns
sub_df = merged_df[selected_columns]

print(f"\nSub-DataFrame with selected columns: {selected_columns}")
display(sub_df)

Sub-DataFrame with selected columns: [' FASTA header', 'location', ' IDR start', ' IDR end']

,FASTA header,location,IDR start,IDR end
0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,N-terminal,1,66
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,middle,306,525
2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,N-terminal,1,34
3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,N-terminal,1,292
4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,middle,415,496
...,...,...,...,...
23611,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-...,C-terminal,332,540
23612,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,N-terminal,1,49
23613,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,C-terminal,309,341
23614,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,IDP,1,115
23615,sp|Q9XFB0|YAB2_ARATH Putative axial regulator ...,N-terminal,1,115

In [6]:
sub_df.to_csv('/home/wenyuantong/Desktop/data/IDR_featurize_annotate_arabi.csv', index=False)

In [18]:
# Apply the function to 'col_A' and create a new column 'new_col_C'
sub_df['gene_name'] = sub_df[' FASTA header'].apply(my_function)

print("DataFrame after adding new column:")
#display(sub_df[' FASTA header'][0])
display(sub_df)

DataFrame after adding new column:

/tmp/ipykernel_583245/549274796.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df['gene_name'] = sub_df[' FASTA header'].apply(my_function)

,FASTA header,location,IDR start,IDR end,gene_name
0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,N-terminal,1,66,A0A1P8B415
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,middle,306,525,A0A1P8B415
2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,N-terminal,1,34,A4FVP2
3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,N-terminal,1,292,F4I316
4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,middle,415,496,F4I316
...,...,...,...,...,...
23611,sp|Q9SV09|C3H46_ARATH Zinc finger CCCH domain-...,C-terminal,332,540,Q9SV09
23612,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,N-terminal,1,49,Q9SVC2
23613,sp|Q9SVC2|SY122_ARATH Syntaxin-122 OS=Arabidop...,C-terminal,309,341,Q9SVC2
23614,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,IDP,1,115,Q9SZD3
23615,sp|Q9XFB0|YAB2_ARATH Putative axial regulator ...,N-terminal,1,115,Q9XFB0

In [11]:
# Define a function to apply
def my_function(x):
    # excise and assign gene names as attributes
#for protein in arabi_proteome:
    #name_string = protein.name
    
    # first try and get gene name from the GN= entry in the FASTA header
    try:
        gene_name = x.split('GN=')[1].split()[0]
    except IndexError:
        # if this fails get the UID-assigned identifier which is 
        # typicall gene-name (or close to) followed by species identifier
        # - e.g. P53_HUMAN in instead of TP53. We keep the _HUMAN so records
        # parsed in this way can be easily identified (although) the _HUMAN
        # could be excised 
        gene_name = x.split()[0].split('|')[2]
    return gene_name

In [17]:
def my_function(x):
    parts = x.split('|')
    if len(parts) > 1:
        return parts[1]
    return None

In [19]:
selected_columns = ['gene_name', ' IDR start',' IDR end', 'location' ]

# Create the sub-DataFrame by selecting the specified columns
df_domain = sub_df[selected_columns]

print(f"\nSub-DataFrame with selected columns: {selected_columns}")
display(df_domain)

Sub-DataFrame with selected columns: ['gene_name', ' IDR start', ' IDR end', 'location']

        gene_name   IDR start   IDR end    location
0      A0A1P8B415           1        66  N-terminal
1      A0A1P8B415         306       525      middle
2          A4FVP2           1        34  N-terminal
3          F4I316           1       292  N-terminal
4          F4I316         415       496      middle
...           ...         ...       ...         ...
23611      Q9SV09         332       540  C-terminal
23612      Q9SVC2           1        49  N-terminal
23613      Q9SVC2         309       341  C-terminal
23614      Q9SZD3           1       115         IDP
23615      Q9XFB0           1       115  N-terminal

[23616 rows x 4 columns]

In [20]:
df_domain.to_csv('/home/wenyuantong/Desktop/data/IDR_arabi_domain.csv', index=False)

In [22]:
output_file_path = '/home/wenyuantong/Desktop/data/IDR_arabi_domain.tsv'
df_domain.to_csv(output_file_path, sep='\t', header=False, index=False)

print(f"DataFrame saved to {output_file_path} without column names and index.")

DataFrame saved to /home/wenyuantong/Desktop/data/IDR_arabi_domain.tsv without column names and index.

In [ ]:










#psytec below

In [23]:

# Replace 'your_file.csv' with the actual path to your CSV file
csv_file_path = '/home/wenyuantong/Desktop/data/psytec_IDR_location.csv'

try:
    # Read the CSV file into a DataFrame
    merged_df = pd.read_csv(csv_file_path)

    print(f"Successfully loaded '{csv_file_path}' into a DataFrame.")
    # Display the first 5 rows of the DataFrame
    display(merged_df.head())

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Successfully loaded '/home/wenyuantong/Desktop/data/psytec_IDR_location.csv' into a DataFrame.

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,0,HopX1a <unknown description>_1_88,HopX1a <unknown description>,1,88,88,28.94,70.23,0.439,0.554,...,0.057,0.091,0.034,0.125,0.432,0.250,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAG...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,N-terminal
1,1,HopX1a <unknown description>_200_247,HopX1a <unknown description>,200,247,48,19.47,47.56,0.427,0.548,...,0.167,0.083,0.042,0.083,0.333,0.292,SPREKIHLAEQPGKDHVWAETDNSSAGSSPIVMDPWSNGAAILAEDSR,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,Middle
2,2,HopX1a <unknown description>_298_380,HopX1a <unknown description>,298,380,83,27.59,66.03,0.435,0.550,...,0.120,0.181,0.024,0.072,0.253,0.349,NVSPLEGGRYQPEKSVLDEAFARRVSDKLNSDDPRRALQMEIEAV...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,C-terminal
3,3,HopX1c <unknown description>_1_87,HopX1c <unknown description>,1,87,87,28.95,70.08,0.427,0.550,...,0.046,0.080,0.034,0.161,0.437,0.241,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESS...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385,N-terminal
4,4,HopX1c <unknown description>_212_267,HopX1c <unknown description>,212,267,56,20.48,48.39,0.425,0.535,...,0.196,0.071,0.089,0.018,0.393,0.232,ASTEEDHVWAETDESQSGTSTIVMDPWSNGSAIFAEDSRFAKNRN...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385,Middle

In [24]:
# Specify the columns you want to include in the sub-DataFrame
#ProteinID,RegionID,Start,Stop
#DDX3X,N-IDR,0,142
#protein_x,region3,24,72
selected_columns = [' FASTA header', 'location', ' IDR start',' IDR end' ]

# Create the sub-DataFrame by selecting the specified columns
sub_df = merged_df[selected_columns]

print(f"\nSub-DataFrame with selected columns: {selected_columns}")
display(sub_df)

Sub-DataFrame with selected columns: [' FASTA header', 'location', ' IDR start', ' IDR end']

                     FASTA header    location   IDR start   IDR end
0    HopX1a <unknown description>  N-terminal           1        88
1    HopX1a <unknown description>      Middle         200       247
2    HopX1a <unknown description>  C-terminal         298       380
3    HopX1c <unknown description>  N-terminal           1        87
4    HopX1c <unknown description>      Middle         212       267
..                            ...         ...         ...       ...
588  HopZ5a <unknown description>  N-terminal           1        44
589  HopZ5a <unknown description>  C-terminal         252       346
590  HopZ5b <unknown description>  N-terminal           1        44
591  HopZ5b <unknown description>  C-terminal         283       346
592  AvrB1b <unknown description>  N-terminal           1        31

[593 rows x 4 columns]

In [25]:
sub_df.to_csv('/home/wenyuantong/Desktop/data/IDR_featurize_annotate_psytec.csv', index=False)

In [30]:
# Apply the function to 'col_A' and create a new column 'new_col_C'
sub_df['gene_name'] = sub_df[' FASTA header'].apply(my_function)

print("DataFrame after adding new column:")
#display(sub_df[' FASTA header'][0])
display(sub_df)

DataFrame after adding new column:

/tmp/ipykernel_583245/549274796.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df['gene_name'] = sub_df[' FASTA header'].apply(my_function)

                     FASTA header    location   IDR start   IDR end gene_name
0    HopX1a <unknown description>  N-terminal           1        88   HopX1a
1    HopX1a <unknown description>      Middle         200       247   HopX1a
2    HopX1a <unknown description>  C-terminal         298       380   HopX1a
3    HopX1c <unknown description>  N-terminal           1        87   HopX1c
4    HopX1c <unknown description>      Middle         212       267   HopX1c
..                            ...         ...         ...       ...       ...
588  HopZ5a <unknown description>  N-terminal           1        44   HopZ5a
589  HopZ5a <unknown description>  C-terminal         252       346   HopZ5a
590  HopZ5b <unknown description>  N-terminal           1        44   HopZ5b
591  HopZ5b <unknown description>  C-terminal         283       346   HopZ5b
592  AvrB1b <unknown description>  N-terminal           1        31   AvrB1b

[593 rows x 5 columns]

In [29]:
def my_function(x):
    parts = x.split('<')
    if len(parts) > 1:
        return parts[0]
    return None

In [31]:
selected_columns = ['gene_name', ' IDR start',' IDR end', 'location' ]

# Create the sub-DataFrame by selecting the specified columns
df_domain = sub_df[selected_columns]

print(f"\nSub-DataFrame with selected columns: {selected_columns}")
display(df_domain)

Sub-DataFrame with selected columns: ['gene_name', ' IDR start', ' IDR end', 'location']

    gene_name   IDR start   IDR end    location
0     HopX1a            1        88  N-terminal
1     HopX1a          200       247      Middle
2     HopX1a          298       380  C-terminal
3     HopX1c            1        87  N-terminal
4     HopX1c          212       267      Middle
..        ...         ...       ...         ...
588   HopZ5a            1        44  N-terminal
589   HopZ5a          252       346  C-terminal
590   HopZ5b            1        44  N-terminal
591   HopZ5b          283       346  C-terminal
592   AvrB1b            1        31  N-terminal

[593 rows x 4 columns]

In [32]:
output_file_path = '/home/wenyuantong/Desktop/data/IDR_psytec_domain.tsv'
df_domain.to_csv(output_file_path, sep='\t', header=False, index=False)

print(f"DataFrame saved to {output_file_path} without column names and index.")

DataFrame saved to /home/wenyuantong/Desktop/data/IDR_psytec_domain.tsv without column names and index.