In [1]:

import numpy as np
import matplotlib

import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
	
# Set such that PDF fonts export in a manner that they
# are editable in illustrator/affinity
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42

# set to define axes linewidths
matplotlib.rcParams['axes.linewidth'] = 0.5

# this defines some prefactors so inline figures look nice
%matplotlib inline
%config InlineBackend.figure_format='retina'


#matplotlib.rc('font', **font)

from tqdm import tqdm
import pickle
from sparrow import Protein
import protfasta
from tqdm.auto import tqdm

IndentationError: unexpected indent (2921902065.py, line 23)

In [2]:
from shephard.apis import uniprot
from shephard.interfaces import si_domains, si_protein_attributes

from finches import Mpipi_frontend, CALVADOS_frontend
mf = Mpipi_frontend()
cf = CALVADOS_frontend()

/home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages/finches/forcefields/calvados.py:236: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.038286503882254706' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  r.loc['H','q'] = 1. / ( 1 + 10**(self.pH-6) )

In [3]:
HP = uniprot.uniprot_fasta_to_proteome('/home/wenyuantong/Desktop/data/UP000006548_3702.fasta')

In [6]:
mode = 'mpipi'

In [7]:
si_domains.add_domains_from_file(HP, '/home/wenyuantong/Desktop/data/IDR_arabi_domain.tsv', skip_bad=True, safe=False)

In [8]:
HP.domains[0]

|Domain: N-terminal (1-66, len=66) in protein A0A1P8B415

In [24]:
# build set of domains to work with - default in paper is IDRs between 100 and 150 inclusive
LOWER = 351
UPPER = 400
size_d = []
for d in HP.domains:
    #display(d)
    if len(d) >= LOWER and len(d) <= UPPER:
        size_d.append(d)

In [25]:
display(len(size_d))

282

In [26]:
# build set of domains to work with - default in paper is IDRs between 100 and 150 inclusive
LOWER = 401
#UPPER = 200
size_d = []
for d in HP.domains:
    #display(d)
    if len(d) >= LOWER:
        size_d.append(d)

In [27]:
display(len(size_d))

680

In [28]:
HP = uniprot.uniprot_fasta_to_proteome('/home/wenyuantong/Desktop/data/PsyTEC_2_new.fasta')

In [29]:
si_domains.add_domains_from_file(HP, '/home/wenyuantong/Desktop/data/IDR_psytec_domain.tsv', skip_bad=True, safe=False)

In [30]:
HP.domains[0]

|Domain: N-terminal (1-88, len=88) in protein HopX1a

In [39]:
# build set of domains to work with - default in paper is IDRs between 100 and 150 inclusive
LOWER = 201
UPPER = 250
size_d = []
for d in HP.domains:
    #display(d)
    if len(d) >= LOWER and len(d) <= UPPER:
        size_d.append(d)

In [40]:
display(len(size_d))

22

In [41]:
# build set of domains to work with - default in paper is IDRs between 100 and 150 inclusive
LOWER = 251
#UPPER = 200
size_d = []
for d in HP.domains:
    #display(d)
    if len(d) >= LOWER:
        size_d.append(d)

In [42]:
display(len(size_d))

17

In [44]:
import pandas as pd

import numpy as np

In [51]:
# Replace 'your_file.csv' with the actual path to your CSV file
csv_file_path = '/home/wenyuantong/Desktop/data/psytec_IDR_merged_df.csv'

try:
    # Read the CSV file into a DataFrame
    merged_df = pd.read_csv(csv_file_path)

    print(f"Successfully loaded '{csv_file_path}' into a DataFrame.")
    # Display the first 5 rows of the DataFrame
    display(merged_df.head())

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Successfully loaded '/home/wenyuantong/Desktop/data/psytec_IDR_merged_df.csv' into a DataFrame.

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,kappa,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length
0,0,HopX1a <unknown description>_1_88,HopX1a <unknown description>,1,88,88,28.94,70.23,0.439,0.554,...,0.224,0.057,0.091,0.034,0.125,0.432,0.250,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAG...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381
1,1,HopX1a <unknown description>_200_247,HopX1a <unknown description>,200,247,48,19.47,47.56,0.427,0.548,...,0.148,0.167,0.083,0.042,0.083,0.333,0.292,SPREKIHLAEQPGKDHVWAETDNSSAGSSPIVMDPWSNGAAILAEDSR,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381
2,2,HopX1a <unknown description>_298_380,HopX1a <unknown description>,298,380,83,27.59,66.03,0.435,0.550,...,0.198,0.120,0.181,0.024,0.072,0.253,0.349,NVSPLEGGRYQPEKSVLDEAFARRVSDKLNSDDPRRALQMEIEAV...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381
3,3,HopX1c <unknown description>_1_87,HopX1c <unknown description>,1,87,87,28.95,70.08,0.427,0.550,...,0.180,0.046,0.080,0.034,0.161,0.437,0.241,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESS...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385
4,4,HopX1c <unknown description>_212_267,HopX1c <unknown description>,212,267,56,20.48,48.39,0.425,0.535,...,0.305,0.196,0.071,0.089,0.018,0.393,0.232,ASTEEDHVWAETDESQSGTSTIVMDPWSNGSAIFAEDSRFAKNRN...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385

In [49]:
# Find the row with the maximum value in 'col1'
row_with_max_col1 = df.loc[df[' IDR len'].idxmax()]

# Get the value from 'col3' in that row
name_with_max_value = row_with_max_col1['IDR ID']

print(f"Name associated with the maximum value in 'col1': {name_with_max_value}")

Name associated with the maximum value in 'col1': AvrE1n <unknown description>_1_408

In [52]:
# Define the conditions
conditions = [
    # First condition: 'IDR start' between 1 and 20 (inclusive) and 'IDR end' less than 'sequence length'
    (merged_df[' IDR start'] >= 1) & (merged_df[' IDR start'] <= 20) & (merged_df[' IDR end'] < merged_df['Sequence Length']),
    # Second condition: 'IDR start' is 1 and 'IDR end' is equal to 'sequence length'
    (merged_df[' IDR start'] == 1) & (merged_df[' IDR end'] == merged_df['Sequence Length']),
    # Third condition: 'IDR start' is greater than 1 and 'IDR end' is between 'sequence length' and 20 before (inclusive)
    (merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] <= merged_df['Sequence Length']) & (merged_df[' IDR end'] >= merged_df['Sequence Length'] - 20),
    # Fourth condition: 'IDR start' is greater than 1 and 'IDR end' is less than 'sequence length' (and not covered by the third condition)
    #(merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] < merged_df['Sequence Length']) & (merged_df[' IDR end'] < merged_df['Sequence Length'] - 20)
    (merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] < merged_df['Sequence Length']) &
    ~((merged_df[' IDR start'] >= 1) & (merged_df[' IDR start'] <= 20)) & # Exclude first condition's start range
    ~((merged_df[' IDR end'] <= merged_df['Sequence Length']) & (merged_df[' IDR end'] >= merged_df['Sequence Length'] - 20)) # Exclude third condition's end range
]

# Define the corresponding values for the new 'location' column
values = ['N-terminal', 'IDP', 'C-terminal', 'Middle']

# Create the new 'location' column using np.select
merged_df['location'] = np.select(conditions, values, default='unknown') # 'unknown' for cases that don't match any condition

print("\nDataFrame with 'location' column:")
display(merged_df.head())

DataFrame with 'location' column:

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,0,HopX1a <unknown description>_1_88,HopX1a <unknown description>,1,88,88,28.94,70.23,0.439,0.554,...,0.057,0.091,0.034,0.125,0.432,0.250,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAG...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,N-terminal
1,1,HopX1a <unknown description>_200_247,HopX1a <unknown description>,200,247,48,19.47,47.56,0.427,0.548,...,0.167,0.083,0.042,0.083,0.333,0.292,SPREKIHLAEQPGKDHVWAETDNSSAGSSPIVMDPWSNGAAILAEDSR,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,Middle
2,2,HopX1a <unknown description>_298_380,HopX1a <unknown description>,298,380,83,27.59,66.03,0.435,0.550,...,0.120,0.181,0.024,0.072,0.253,0.349,NVSPLEGGRYQPEKSVLDEAFARRVSDKLNSDDPRRALQMEIEAV...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,C-terminal
3,3,HopX1c <unknown description>_1_87,HopX1c <unknown description>,1,87,87,28.95,70.08,0.427,0.550,...,0.046,0.080,0.034,0.161,0.437,0.241,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESS...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385,N-terminal
4,4,HopX1c <unknown description>_212_267,HopX1c <unknown description>,212,267,56,20.48,48.39,0.425,0.535,...,0.196,0.071,0.089,0.018,0.393,0.232,ASTEEDHVWAETDESQSGTSTIVMDPWSNGSAIFAEDSRFAKNRN...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385,Middle

In [ ]:
# Filter the DataFrame for rows where 'location' is 'unknown'
unknown_location_df = merged_df[merged_df['location'] == 'IDP']

print("\nDataFrame with only 'unknown' locations:")
display(unknown_location_df)

In [58]:
# Define the conditions
conditions = [
    # First condition: 'IDR start' between 1 and 20 (inclusive) and 'IDR end' less than 'sequence length'
    (merged_df[' IDR start'] == 1) & (merged_df[' IDR end'] < merged_df['Sequence Length']),
    # Second condition: 'IDR start' is 1 and 'IDR end' is equal to 'sequence length'
    (merged_df[' IDR start'] == 1) & (merged_df[' IDR end'] == merged_df['Sequence Length']),
    # Third condition: 'IDR start' is greater than 1 and 'IDR end' is between 'sequence length' and 20 before (inclusive)
    (merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] == merged_df['Sequence Length']),
    # Fourth condition: 'IDR start' is greater than 1 and 'IDR end' is less than 'sequence length' (and not covered by the third condition)
    #(merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] < merged_df['Sequence Length']) & (merged_df[' IDR end'] < merged_df['Sequence Length'] - 20)
    (merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] < merged_df['Sequence Length']) 
]

# Define the corresponding values for the new 'location' column
values = ['N-terminal', 'IDP', 'C-terminal', 'Middle']

# Create the new 'location' column using np.select
merged_df['location'] = np.select(conditions, values, default='unknown') # 'unknown' for cases that don't match any condition

print("\nDataFrame with 'location' column:")
display(merged_df.head())

DataFrame with 'location' column:

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,0,HopX1a <unknown description>_1_88,HopX1a <unknown description>,1,88,88,28.94,70.23,0.439,0.554,...,0.057,0.091,0.034,0.125,0.432,0.250,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAG...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,N-terminal
1,1,HopX1a <unknown description>_200_247,HopX1a <unknown description>,200,247,48,19.47,47.56,0.427,0.548,...,0.167,0.083,0.042,0.083,0.333,0.292,SPREKIHLAEQPGKDHVWAETDNSSAGSSPIVMDPWSNGAAILAEDSR,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,Middle
2,2,HopX1a <unknown description>_298_380,HopX1a <unknown description>,298,380,83,27.59,66.03,0.435,0.550,...,0.120,0.181,0.024,0.072,0.253,0.349,NVSPLEGGRYQPEKSVLDEAFARRVSDKLNSDDPRRALQMEIEAV...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,Middle
3,3,HopX1c <unknown description>_1_87,HopX1c <unknown description>,1,87,87,28.95,70.08,0.427,0.550,...,0.046,0.080,0.034,0.161,0.437,0.241,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESS...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385,N-terminal
4,4,HopX1c <unknown description>_212_267,HopX1c <unknown description>,212,267,56,20.48,48.39,0.425,0.535,...,0.196,0.071,0.089,0.018,0.393,0.232,ASTEEDHVWAETDESQSGTSTIVMDPWSNGSAIFAEDSRFAKNRN...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385,Middle

In [63]:
# Filter the DataFrame for rows where 'location' is 'unknown'
unknown_location_df = merged_df[merged_df['location'] == 'IDP']

#print("\nDataFrame with only 'unknown' locations:")
display(unknown_location_df)

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
421,421,AvrE1q <unknown description>_1_258,AvrE1q <unknown description>,1,258,258,53.50,126.41,0.415,0.558,...,0.093,0.124,0.019,0.070,0.426,0.267,MHSSSIHRNTGSIIQPPVPANTNAATDLQQKIEQPKQRSSHSLSS...,MHSSSIHRNTGSIIQPPVPANTNAATDLQQKIEQPKQRSSHSLSSV...,258,IDP
432,432,AvrPto1g <unknown description>_1_160,AvrPto1g <unknown description>,1,160,160,34.70,82.36,0.379,0.491,...,0.087,0.087,0.056,0.056,0.425,0.281,MGNNCVGGATSARQVYSPDRVSNSSDDPNHLTASQLLNVRQQLAE...,MGNNCVGGATSARQVYSPDRVSNSSDDPNHLTASQLLNVRQQLAES...,160,IDP
433,433,AvrPto1j <unknown description>_1_267,AvrPto1j <unknown description>,1,267,267,48.14,116.31,0.388,0.525,...,0.082,0.090,0.052,0.064,0.434,0.266,MGGLVQSPPPVGANRSHSTGRGRSNLLSATHRVCPGGMTQTKGSP...,MGGLVQSPPPVGANRSHSTGRGRSNLLSATHRVCPGGMTQTKGSPI...,267,IDP
437,437,AvrRpm1g <unknown description>_1_229,AvrRpm1g <unknown description>,1,229,229,43.46,99.61,0.397,0.520,...,0.122,0.118,0.079,0.031,0.419,0.231,MGYNVSNTSRNTGYYSGYESHQEPRGASSSSGNQHRGYEADSEQS...,MGYNVSNTSRNTGYYSGYESHQEPRGASSSSGNQHRGYEADSEQSG...,229,IDP
476,476,HopAG1e <unknown description>_1_57,HopAG1e <unknown description>,1,57,57,20.74,49.01,0.415,0.525,...,0.053,0.088,0.088,0.070,0.456,0.246,MNPITHSFNHLGFSNAQSTSALAPGGNKVPNFVSRGRGQGIPLEH...,MNPITHSFNHLGFSNAQSTSALAPGGNKVPNFVSRGRGQGIPLEHF...,57,IDP
479,479,HopAG1n <unknown description>_1_111,HopAG1n <unknown description>,1,111,111,30.20,70.71,0.406,0.529,...,0.108,0.126,0.081,0.063,0.369,0.243,MINPVKHNFSHLGFSNAQSTSALGPASNKVPNFVSRGRGKGVPVE...,MINPVKHNFSHLGFSNAQSTSALGPASNKVPNFVSRGRGKGVPVEQ...,111,IDP
481,481,HopAH1aa <unknown description>_1_86,HopAH1aa <unknown description>,1,86,86,27.31,65.95,0.422,0.547,...,0.058,0.058,0.047,0.093,0.558,0.186,MSMNTSVSNNSPGWSPVSSGNQAPSPDYSGKSSSNAVHFLPPEST...,MSMNTSVSNNSPGWSPVSSGNQAPSPDYSGKSSSNAVHFLPPESTQ...,86,IDP
484,484,HopAI1f <unknown description>_1_69,HopAI1f <unknown description>,1,69,69,24.92,61.44,0.422,0.566,...,0.072,0.130,0.029,0.087,0.348,0.333,MPLSKPMLSLKLNTQLTSPPVKKDTGAELSRLNKGEVLANTQTRF...,MPLSKPMLSLKLNTQLTSPPVKKDTGAELSRLNKGEVLANTQTRFA...,69,IDP
485,485,HopAI1h <unknown description>_1_75,HopAI1h <unknown description>,1,75,75,25.78,63.85,0.423,0.564,...,0.040,0.173,0.040,0.080,0.293,0.373,MPINRPAFNLKLNTAIAQPTVKKDAGAELRRLNQSEVRANTQTRF...,MPINRPAFNLKLNTAIAQPTVKKDAGAELRRLNQSEVRANTQTRFA...,75,IDP
487,487,HopAI1l <unknown description>_1_54,HopAI1l <unknown description>,1,54,54,20.94,51.66,0.429,0.551,...,0.056,0.167,0.037,0.074,0.333,0.333,MPINRPAFNLKLNTAIAQPTVKKDAGAELRRLNQSEVRANTQTRF...,MPINRPAFNLKLNTAIAQPTVKKDAGAELRRLNQSEVRANTQTRFA...,54,IDP
488,488,HopAI1n <unknown description>_1_94,HopAI1n <unknown description>,1,94,94,27.39,65.57,0.408,0.519,...,0.064,0.160,0.064,0.053,0.362,0.298,MPINRPAFNLKLNTAIAQPTVKKDAGAELRRLNQSEVRANTQTRF...,MPINRPAFNLKLNTAIAQPTVKKDAGAELRRLNQSEVRANTQTRFA...,94,IDP
491,491,HopAS1g <unknown description>_1_82,HopAS1g <unknown description>,1,82,82,29.22,69.58,0.454,0.567,...,0.037,0.110,0.024,0.146,0.415,0.268,MTLRINTRSATPVVPLETGSSSQPAVPSVTARPTEPPPVANPAAP...,MTLRINTRSATPVVPLETGSSSQPAVPSVTARPTEPPPVANPAAPK...,82,IDP
497,497,HopAT1h <unknown description>_1_122,HopAT1h <unknown description>,1,122,122,33.55,78.10,0.407,0.521,...,0.098,0.098,0.033,0.098,0.393,0.270,MIKANSWSSNLNAYRILQEPQSLTEEPPPIQTICPVQPESMAPPE...,MIKANSWSSNLNAYRILQEPQSLTEEPPPIQTICPVQPESMAPPEH...,122,IDP
498,498,HopAU1b <unknown description>_1_88,HopAU1b <unknown description>,1,88,88,28.52,68.27,0.430,0.559,...,0.091,0.068,0.023,0.045,0.432,0.330,MKPVQSVSATQHYNPLTNLGQEASCSHEISGITQTEGMQATAATT...,MKPVQSVSATQHYNPLTNLGQEASCSHEISGITQTEGMQATAATTQ...,88,IDP
499,499,HopAZ1n <unknown description>_1_89,HopAZ1n <unknown description>,1,89,89,27.80,64.58,0.413,0.528,...,0.135,0.124,0.101,0.079,0.326,0.236,MTYGIRGGVGTSAYYTQPQPFDELKLKPEQIQEKTAKLMEKGYFT...,MTYGIRGGVGTSAYYTQPQPFDELKLKPEQIQEKTAKLMEKGYFTV...,89,IDP
500,500,HopAZ1s <unknown description>_1_145,HopAZ1s <unknown description>,1,145,145,37.41,88.70,0.423,0.542,...,0.090,0.152,0.062,0.069,0.359,0.262,MTYGIRGGVGTSAYYTQPQPFDELKLKPEQIQEKTAKLMEKGYFT...,MTYGIRGGVGTSAYYTQPQPFDELKLKPEQIQEKTAKLMEKGYFTV...,145,IDP
501,501,HopB1c <unknown description>_1_171,HopB1c <unknown description>,1,171,171,40.98,97.84,0.417,0.542,...,0.099,0.135,0.047,0.111,0.327,0.251,MRPVGGPAPGYYPPTYEAERPTAQAGNDRARSSQASSSPAASVAP...,MRPVGGPAPGYYPPTYEAERPTAQAGNDRARSSQASSSPAASVAPE...,171,IDP
505,505,HopBA1b <unknown description>_1_66,HopBA1b <unknown description>,1,66,66,23.33,56.87,0.410,0.547,...,0.061,0.136,0.061,0.015,0.212,0.485,MVVEQPKTTMQKILYMKKRLALNAAWDAAAAREASAVCANKSMVW...,MVVEQPKTTMQKILYMKKRLALNAAWDAAAAREASAVCANKSMVWA...,66,IDP
519,519,HopBP1d <unknown description>_1_82,HopBP1d <unknown description>,1,82,82,24.84,56.78,0.399,0.510,...,0.061,0.122,0.061,0.049,0.488,0.220,MNISGLNRRQGTQAENTEGASSSVNTPQPQRGAGRRLQRQDALPT...,MNISGLNRRQGTQAENTEGASSSVNTPQPQRGAGRRLQRQDALPTD...,82,IDP
522,522,HopBR1a <unknown description>_1_133,HopBR1a <unknown description>,1,133,133,33.40,78.59,0.418,0.520,...,0.053,0.098,0.075,0.045,0.398,0.316,MPKISSFFGGGSSVQSFDATVQHYHSDETVHGTFNASQLGLHSYQ...,MPKISSFFGGGSSVQSFDATVQHYHSDETVHGTFNASQLGLHSYQR...,133,IDP
523,523,HopBS1a <unknown description>_1_52,HopBS1a <unknown description>,1,52,52,22.61,53.04,0.462,0.564,...,0.096,0.038,0.038,0.115,0.365,0.327,MIKANSWSSNLDAYRILQGPESLTEELPPIQTICLVQPESMAPPS...,MIKANSWSSNLDAYRILQGPESLTEELPPIQTICLVQPESMAPPSI...,52,IDP
537,537,HopF3b <unknown description>_1_96,HopF3b <unknown description>,1,96,96,28.79,68.67,0.408,0.539,...,0.083,0.125,0.073,0.062,0.417,0.219,MGICASSSRNQYSPTVSSTCSPQHVASHGNLASSGGNRITSVDQL...,MGICASSSRNQYSPTVSSTCSPQHVASHGNLASSGGNRITSVDQLN...,96,IDP
539,539,HopG1e <unknown description>_1_96,HopG1e <unknown description>,1,96,96,27.78,60.28,0.420,0.523,...,0.042,0.115,0.125,0.031,0.406,0.281,MQIKNSHLYSASRMVQNTFNASPKIEATNTIAKNNEPAAMSATQT...,MQIKNSHLYSASRMVQNTFNASPKIEATNTIAKNNEPAAMSATQTA...,96,IDP
540,540,HopG1f <unknown description>_1_78,HopG1f <unknown description>,1,78,78,25.00,59.01,0.431,0.544,...,0.051,0.115,0.051,0.000,0.487,0.295,MQIRNSHLYSASRLVQNTFNASSTKEAANTIAKNNESAALSATQT...,MQIRNSHLYSASRLVQNTFNASSTKEAANTIAKNNESAALSATQTA...,78,IDP
554,554,HopM1i <unknown description>_1_61,HopM1i <unknown description>,1,61,61,23.99,57.55,0.459,0.548,...,0.033,0.115,0.000,0.131,0.426,0.295,MNTPRIGGSGGIELARINQQHDAISAQTAHPNAVTPGMNPPLTPI...,MNTPRIGGSGGIELARINQQHDAISAQTAHPNAVTPGMNPPLTPIR...,61,IDP
559,559,HopO1e <unknown description>_1_54,HopO1e <unknown description>,1,54,54,20.96,51.29,0.426,0.536,...,0.204,0.185,0.074,0.074,0.204,0.259,MIVQERKRLKSQPKSLASDIERPDSMIKKAFDEKDGHPFGERFSD...,MIVQERKRLKSQPKSLASDIERPDSMIKKAFDEKDGHPFGERFSDD...,54,IDP
581,581,HopX1j <unknown description>_1_382,HopX1j <unknown description>,1,382,382,60.88,143.37,0.395,0.533,...,0.123,0.123,0.039,0.055,0.335,0.319,MRIHSSGHGISGPVSSAETVEKAVQSSAQAQNEASHSGPSEHPES...,MRIHSSGHGISGPVSSAETVEKAVQSSAQAQNEASHSGPSEHPESR...,382,IDP
584,584,HopZ1f <unknown description>_1_59,HopZ1f <unknown description>,1,59,59,22.70,54.43,0.426,0.549,...,0.102,0.169,0.017,0.068,0.390,0.237,MGNVCVSGSRMSQHVYSPERADAPPRSTLNTTERSQRTAGDADRN...,MGNVCVSGSRMSQHVYSPERADAPPRSTLNTTERSQRTAGDADRNH...,59,IDP
587,587,HopZ1k <unknown description>_1_99,HopZ1k <unknown description>,1,99,99,28.64,70.40,0.427,0.542,...,0.081,0.152,0.061,0.040,0.374,0.293,MKAYGQAAIDRASGKKTSASFAKLDATHLLDMINAENQRNSDLNL...,MKAYGQAAIDRASGKKTSASFAKLDATHLLDMINAENQRNSDLNLR...,99,IDP

In [66]:
# Get the column as a pandas Series
column_entries = unknown_location_df['IDR ID']

# Define the substring to remove
substring_to_remove = '<unknown description>'

# Remove the substring from each entry and convert to a list
cleaned_list = column_entries.astype(str).str.replace(substring_to_remove, '').tolist()

print("Cleaned list:")
print(cleaned_list)

Cleaned list:
['AvrE1q _1_258', 'AvrPto1g _1_160', 'AvrPto1j _1_267', 'AvrRpm1g _1_229', 'HopAG1e _1_57', 'HopAG1n _1_111', 'HopAH1aa _1_86', 'HopAI1f _1_69', 'HopAI1h _1_75', 'HopAI1l _1_54', 'HopAI1n _1_94', 'HopAS1g _1_82', 'HopAT1h _1_122', 'HopAU1b _1_88', 'HopAZ1n _1_89', 'HopAZ1s _1_145', 'HopB1c _1_171', 'HopBA1b _1_66', 'HopBP1d _1_82', 'HopBR1a _1_133', 'HopBS1a _1_52', 'HopF3b _1_96', 'HopG1e _1_96', 'HopG1f _1_78', 'HopM1i _1_61', 'HopO1e _1_54', 'HopX1j _1_382', 'HopZ1f _1_59', 'HopZ1k _1_99']

In [67]:
print("Cleaned list:")
for item in cleaned_list:
    print(item)

Cleaned list:
AvrE1q _1_258
AvrPto1g _1_160
AvrPto1j _1_267
AvrRpm1g _1_229
HopAG1e _1_57
HopAG1n _1_111
HopAH1aa _1_86
HopAI1f _1_69
HopAI1h _1_75
HopAI1l _1_54
HopAI1n _1_94
HopAS1g _1_82
HopAT1h _1_122
HopAU1b _1_88
HopAZ1n _1_89
HopAZ1s _1_145
HopB1c _1_171
HopBA1b _1_66
HopBP1d _1_82
HopBR1a _1_133
HopBS1a _1_52
HopF3b _1_96
HopG1e _1_96
HopG1f _1_78
HopM1i _1_61
HopO1e _1_54
HopX1j _1_382
HopZ1f _1_59
HopZ1k _1_99

In [78]:
processed_strings = []
for s in cleaned_list:
    # Split the string at the first space and take the first part
    front_part = s.split(' ', 1)[0]
    processed_strings.append(front_part)

print("\nProcessed list (front part only):")
print(processed_strings)

Processed list (front part only):
['AvrE1q', 'AvrPto1g', 'AvrPto1j', 'AvrRpm1g', 'HopAG1e', 'HopAG1n', 'HopAH1aa', 'HopAI1f', 'HopAI1h', 'HopAI1l', 'HopAI1n', 'HopAS1g', 'HopAT1h', 'HopAU1b', 'HopAZ1n', 'HopAZ1s', 'HopB1c', 'HopBA1b', 'HopBP1d', 'HopBR1a', 'HopBS1a', 'HopF3b', 'HopG1e', 'HopG1f', 'HopM1i', 'HopO1e', 'HopX1j', 'HopZ1f', 'HopZ1k']

In [129]:
feat_df = pd.read_csv('/home/wenyuantong/Desktop/data/IDR_psytec_domain.tsv', sep='\t',header=None)

In [182]:
feat_df

           0    1    2           3
0    HopX1a     1   88  N-terminal
1    HopX1a   200  247      Middle
2    HopX1a   298  380  C-terminal
3    HopX1c     1   87  N-terminal
4    HopX1c   212  267      Middle
..       ...  ...  ...         ...
588  HopZ5a     1   44  N-terminal
589  HopZ5a   252  346  C-terminal
590  HopZ5b     1   44  N-terminal
591  HopZ5b   283  346  C-terminal
592  AvrB1b     1   31  N-terminal

[593 rows x 4 columns]

In [164]:
N_df = feat_df[feat_df[3] == 'N-terminal']

#print("\nDataFrame with only 'unknown' locations:")
display(N_df)

           0  1    2           3
0    HopX1a   1   88  N-terminal
3    HopX1c   1   87  N-terminal
5    HopX1b   1   74  N-terminal
7    HopX1i   1  158  N-terminal
9    HopX1e   1  382  N-terminal
..       ... ..  ...         ...
582  HopX1k   1  157  N-terminal
585  HopZ1h   1   49  N-terminal
588  HopZ5a   1   44  N-terminal
590  HopZ5b   1   44  N-terminal
592  AvrB1b   1   31  N-terminal

[330 rows x 4 columns]

In [74]:
# Get unique entries from each column
set_A = set(N_df[0])
set_B = set(feat_df[0])

# Find entries that are in A but not in B, or in B but not in A
# This is the symmetric difference (elements unique to each set)
not_in_both = list(set_A.symmetric_difference(set_B))

In [76]:
print(len(not_in_both))

84

In [77]:
for item in not_in_both:
    print(item)

HopI1a
HopG1e
HopM1i
HopAI1e
HopAA1o
HopAB1c
HopI1j
AvrRpm1g
HopAT1h
HopI1d
HopI1p
HopBA1b
HopAG1e
HopD2e
HopBS1a
HopA1c
HopAI1k
HopI1h
HopH1c
HopB2m
HopX1f
HopI1o
HopI1s
HopI1c
HopAI1d
HopAI1c
HopY1e
HopM1ac
HopA1l
HopL1a
HopI1k
HopZ1k
HopAT1d
HopAU1b
HopD2h
HopY1c
AvrPto1j
HopAI1m
AvrE1q
HopAT1f
HopY1f
HopBL1a
HopB1c
HopAH1aa
HopZ1f
HopI1l
HopZ4a
HopM1w
HopAI1i
HopI1f
HopAT1e
HopA1a
HopI1e
HopY1b
HopBP1d
HopAZ1s
HopAI1f
HopX1j
HopI1m
HopI1i
HopBR1a
HopAI1l
HopB2d
HopAA1c
HopAS1g
HopAB1w
HopA1g
HopO1e
HopAI1b
HopAT1a
HopI1n
HopAI1n
HopAI1g
HopI1g
HopI1b
HopG1f
HopA1q
AvrPto1g
HopAZ1n
HopAI1h
HopAA1f
HopAG1n
HopF3b
HopAI1a

In [91]:
processed_strings2 = []
for s in not_in_both:
    # Split the string at the first space and take the first part
    front_part = s.split(' ', 1)[0]
    processed_strings2.append(front_part)

print("\nProcessed list (front part only):")
print(processed_strings2)

Processed list (front part only):
['HopI1a', 'HopG1e', 'HopM1i', 'HopAI1e', 'HopAA1o', 'HopAB1c', 'HopI1j', 'AvrRpm1g', 'HopAT1h', 'HopI1d', 'HopI1p', 'HopBA1b', 'HopAG1e', 'HopD2e', 'HopBS1a', 'HopA1c', 'HopAI1k', 'HopI1h', 'HopH1c', 'HopB2m', 'HopX1f', 'HopI1o', 'HopI1s', 'HopI1c', 'HopAI1d', 'HopAI1c', 'HopY1e', 'HopM1ac', 'HopA1l', 'HopL1a', 'HopI1k', 'HopZ1k', 'HopAT1d', 'HopAU1b', 'HopD2h', 'HopY1c', 'AvrPto1j', 'HopAI1m', 'AvrE1q', 'HopAT1f', 'HopY1f', 'HopBL1a', 'HopB1c', 'HopAH1aa', 'HopZ1f', 'HopI1l', 'HopZ4a', 'HopM1w', 'HopAI1i', 'HopI1f', 'HopAT1e', 'HopA1a', 'HopI1e', 'HopY1b', 'HopBP1d', 'HopAZ1s', 'HopAI1f', 'HopX1j', 'HopI1m', 'HopI1i', 'HopBR1a', 'HopAI1l', 'HopB2d', 'HopAA1c', 'HopAS1g', 'HopAB1w', 'HopA1g', 'HopO1e', 'HopAI1b', 'HopAT1a', 'HopI1n', 'HopAI1n', 'HopAI1g', 'HopI1g', 'HopI1b', 'HopG1f', 'HopA1q', 'AvrPto1g', 'HopAZ1n', 'HopAI1h', 'HopAA1f', 'HopAG1n', 'HopF3b', 'HopAI1a']

In [176]:
set1 = set(processed_strings)
set2 = set(processed_strings2)

# Find entries that are in either set but not in both (symmetric difference)
not_in_both2 = list(set1.symmetric_difference(set2))

In [177]:
print(len(not_in_both2))

55

In [178]:
#for item in not_in_both2:
    #print(item)

In [96]:
# And entries unique to list 2:
unique_to_list2 = list(set1 - set2)
print(f"Entries unique to List 2: {unique_to_list2}")

Entries unique to List 2: []

In [183]:
# Filter the DataFrame to keep only rows where 'category' is in the list
feat_df[0] = feat_df[0].str.replace(' ', '')
filtered_df_isin = feat_df[feat_df[0].isin(not_in_both2)]

#print(f"\nDataFrame filtered to include only categories: {categories_to_keep}")
display(filtered_df_isin)

           0     1     2           3
39    HopI1c   178   338      Middle
40    HopI1e   180   300      Middle
41    HopI1g   142   284      Middle
42    HopI1o   177   260      Middle
43    HopI1l   178   261      Middle
44    HopI1n   178   258      Middle
45    HopI1d   178   257      Middle
46    HopI1a   178   258      Middle
47    HopI1b   178   258      Middle
48    HopI1j   178   256      Middle
49    HopI1f   178   256      Middle
50    HopI1h   178   334  C-terminal
51    HopI1p   178   308  C-terminal
57   HopAI1a   190   267  C-terminal
58   HopAI1b   192   267  C-terminal
59   HopAI1d   197   267  C-terminal
60   HopAI1g   203   267  C-terminal
61   HopAI1c   203   267  C-terminal
62   HopAI1m   193   267  C-terminal
63   HopAI1k   192   267  C-terminal
132  HopBL1a   402   553      Middle
151   HopH1c    92   221  C-terminal
192   HopB2d  1129  1164      Middle
201  HopAA1c   114   178      Middle
202  HopAA1c   234   486  C-terminal
207  HopAA1f   453   483  C-terminal
210  HopAA1o   452   483  C-terminal
211   HopY1b    66   217      Middle
214   HopY1f    98   218      Middle
215   HopY1c   106   221      Middle
262   HopL1a   668   716      Middle
313   HopZ4a   247   335  C-terminal
361   HopA1l    93   125      Middle
362   HopA1c    98   131      Middle
363   HopA1a   101   132      Middle
364   HopA1g    65   127      Middle
443   HopA1q    65   132      Middle
459  HopAB1c    42   119      Middle
460  HopAB1c   195   226      Middle
473  HopAB1w    84   122      Middle
483  HopAI1e   196   267  C-terminal
486  HopAI1i   154   230  C-terminal
492  HopAT1a   717   762  C-terminal
493  HopAT1d   717   763  C-terminal
494  HopAT1e   507   538      Middle
495  HopAT1e  1075  1124  C-terminal
496  HopAT1f    66    97  C-terminal
504   HopB2m   972  1011  C-terminal
529   HopD2e   152   185  C-terminal
530   HopD2h   157   187  C-terminal
542   HopI1i   180   412      Middle
543   HopI1k   178   257      Middle
544   HopI1m   177   444      Middle
545   HopI1s   179   415      Middle
550  HopM1ac    86   162  C-terminal
557   HopM1w   598   656  C-terminal
578   HopX1f    45    92      Middle
579   HopX1f   134   220  C-terminal
583   HopY1e   106   220      Middle

In [97]:
print(len(unique_to_list2))

0

In [98]:
df = pd.read_excel('/home/wenyuantong/Desktop/data/PsyTEC Allele Master Info Sheet.xlsx',sheet_name="PsyTEC_alleles")

In [114]:
selected_columns = ['Effector', 'Family' ]

# Create the sub-DataFrame by selecting the specified columns
df_fam = df[selected_columns]
df_fam['Effector'] = df_fam['Effector'].str.replace(' ', '')

print(f"\nSub-DataFrame with selected columns: {selected_columns}")
display(df_fam)

Sub-DataFrame with selected columns: ['Effector', 'Family']

/tmp/ipykernel_1299591/3155171919.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fam['Effector'] = df_fam['Effector'].str.replace(' ', '')

    Effector Family
0     HopX1a   HopX
1     HopX1c   HopX
2     HopX1b   HopX
3     HopX1i   HopX
4     HopX1e   HopX
..       ...    ...
525   HopZ1h   HopZ
526   HopZ1k   HopZ
527   HopZ5a   HopZ
528   HopZ5b   HopZ
529   AvrB1b   AvrB

[530 rows x 2 columns]

In [148]:
No_df = feat_df[feat_df[3] != 'N-terminal']
No_df = No_df[feat_df[3] != 'IDP']

/tmp/ipykernel_1299591/2757280745.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  No_df = No_df[feat_df[3] != 'IDP']

In [149]:
display(No_df)

           0    1    2           3
1    HopX1a   200  247      Middle
2    HopX1a   298  380  C-terminal
4    HopX1c   212  267      Middle
6    HopX1b   205  249      Middle
8    HopX1i   215  384  C-terminal
..       ...  ...  ...         ...
579  HopX1f   134  220  C-terminal
583  HopY1e   106  220      Middle
586  HopZ1h   247  369  C-terminal
589  HopZ5a   252  346  C-terminal
591  HopZ5b   283  346  C-terminal

[234 rows x 4 columns]

In [150]:

No_df[0] = No_df[0].str.replace(' ', '')

In [184]:
merged_df = pd.merge(
    filtered_df_isin,
    df_fam,
    left_on=[0],
    right_on=['Effector'],
    how='inner'
)

In [185]:
display(merged_df)

          0     1     2           3 Effector Family
0    HopI1c   178   338      Middle   HopI1c   HopI
1    HopI1e   180   300      Middle   HopI1e   HopI
2    HopI1g   142   284      Middle   HopI1g   HopI
3    HopI1o   177   260      Middle   HopI1o   HopI
4    HopI1l   178   261      Middle   HopI1l   HopI
5    HopI1n   178   258      Middle   HopI1n   HopI
6    HopI1d   178   257      Middle   HopI1d   HopI
7    HopI1a   178   258      Middle   HopI1a   HopI
8    HopI1b   178   258      Middle   HopI1b   HopI
9    HopI1j   178   256      Middle   HopI1j   HopI
10   HopI1f   178   256      Middle   HopI1f   HopI
11   HopI1h   178   334  C-terminal   HopI1h   HopI
12   HopI1p   178   308  C-terminal   HopI1p   HopI
13  HopAI1a   190   267  C-terminal  HopAI1a  HopAI
14  HopAI1b   192   267  C-terminal  HopAI1b  HopAI
15  HopAI1d   197   267  C-terminal  HopAI1d  HopAI
16  HopAI1g   203   267  C-terminal  HopAI1g  HopAI
17  HopAI1c   203   267  C-terminal  HopAI1c  HopAI
18  HopAI1m   193   267  C-terminal  HopAI1m  HopAI
19  HopAI1k   192   267  C-terminal  HopAI1k  HopAI
20  HopBL1a   402   553      Middle  HopBL1a  HopBL
21   HopH1c    92   221  C-terminal   HopH1c   HopH
22   HopB2d  1129  1164      Middle   HopB2d   HopB
23  HopAA1c   114   178      Middle  HopAA1c  HopAA
24  HopAA1c   234   486  C-terminal  HopAA1c  HopAA
25  HopAA1f   453   483  C-terminal  HopAA1f  HopAA
26  HopAA1o   452   483  C-terminal  HopAA1o  HopAA
27   HopY1b    66   217      Middle   HopY1b   HopY
28   HopY1f    98   218      Middle   HopY1f   HopY
29   HopY1c   106   221      Middle   HopY1c   HopY
30   HopL1a   668   716      Middle   HopL1a   HopL
31   HopZ4a   247   335  C-terminal   HopZ4a   HopZ
32   HopA1l    93   125      Middle   HopA1l   HopA
33   HopA1c    98   131      Middle   HopA1c   HopA
34   HopA1a   101   132      Middle   HopA1a   HopA
35   HopA1g    65   127      Middle   HopA1g   HopA
36   HopA1q    65   132      Middle   HopA1q   HopA
37  HopAB1c    42   119      Middle  HopAB1c  HopAB
38  HopAB1c   195   226      Middle  HopAB1c  HopAB
39  HopAB1w    84   122      Middle  HopAB1w  HopAB
40  HopAI1e   196   267  C-terminal  HopAI1e  HopAI
41  HopAI1i   154   230  C-terminal  HopAI1i  HopAI
42  HopAT1a   717   762  C-terminal  HopAT1a  HopAT
43  HopAT1d   717   763  C-terminal  HopAT1d  HopAT
44  HopAT1e   507   538      Middle  HopAT1e  HopAT
45  HopAT1e  1075  1124  C-terminal  HopAT1e  HopAT
46  HopAT1f    66    97  C-terminal  HopAT1f  HopAT
47   HopB2m   972  1011  C-terminal   HopB2m   HopB
48   HopD2e   152   185  C-terminal   HopD2e   HopD
49   HopD2h   157   187  C-terminal   HopD2h   HopD
50   HopI1i   180   412      Middle   HopI1i   HopI
51   HopI1k   178   257      Middle   HopI1k   HopI
52   HopI1m   177   444      Middle   HopI1m   HopI
53   HopI1s   179   415      Middle   HopI1s   HopI
54  HopM1ac    86   162  C-terminal  HopM1ac   HopM
55   HopM1w   598   656  C-terminal   HopM1w   HopM
56   HopX1f    45    92      Middle   HopX1f   HopX
57   HopX1f   134   220  C-terminal   HopX1f   HopX
58   HopY1e   106   220      Middle   HopY1e   HopY

In [186]:
print("Value counts for 'FirstColumn':")
display(merged_df['Family'].value_counts())

Value counts for 'FirstColumn':

Family
HopI     17
HopAI     9
HopA      5
HopAT     5
HopY      4
HopAA     4
HopAB     3
HopM      2
HopX      2
HopB      2
HopD      2
HopH      1
HopBL     1
HopL      1
HopZ      1
Name: count, dtype: int64

In [157]:
IDP_df = feat_df[feat_df[3] == 'IDP']

In [158]:
IDP_df[0] = IDP_df[0].str.replace(' ', '')

/tmp/ipykernel_1299591/2721019566.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IDP_df[0] = IDP_df[0].str.replace(' ', '')

In [159]:
display(IDP_df)

            0  1    2    3
421    AvrE1q  1  258  IDP
432  AvrPto1g  1  160  IDP
433  AvrPto1j  1  267  IDP
437  AvrRpm1g  1  229  IDP
476   HopAG1e  1   57  IDP
479   HopAG1n  1  111  IDP
481  HopAH1aa  1   86  IDP
484   HopAI1f  1   69  IDP
485   HopAI1h  1   75  IDP
487   HopAI1l  1   54  IDP
488   HopAI1n  1   94  IDP
491   HopAS1g  1   82  IDP
497   HopAT1h  1  122  IDP
498   HopAU1b  1   88  IDP
499   HopAZ1n  1   89  IDP
500   HopAZ1s  1  145  IDP
501    HopB1c  1  171  IDP
505   HopBA1b  1   66  IDP
519   HopBP1d  1   82  IDP
522   HopBR1a  1  133  IDP
523   HopBS1a  1   52  IDP
537    HopF3b  1   96  IDP
539    HopG1e  1   96  IDP
540    HopG1f  1   78  IDP
554    HopM1i  1   61  IDP
559    HopO1e  1   54  IDP
581    HopX1j  1  382  IDP
584    HopZ1f  1   59  IDP
587    HopZ1k  1   99  IDP

In [162]:
merged_df = pd.merge(
    IDP_df,
    df_fam,
    left_on=[0],
    right_on=['Effector'],
    how='inner'
)

In [163]:
print("Value counts for 'FirstColumn':")
display(merged_df['Family'].value_counts())

Value counts for 'FirstColumn':

Family
HopAI     4
HopAG     2
HopZ      2
HopAZ     2
AvrPto    2
HopG      2
HopAH     1
AvrE      1
AvrRpm    1
HopAU     1
HopB      1
HopAT     1
HopAS     1
HopBP     1
HopBA     1
HopBS     1
HopBR     1
HopF      1
HopM      1
HopO      1
HopX      1
Name: count, dtype: int64

In [173]:


# Define the range
lower_bound = 250
#upper_bound = 249

# Filter the DataFrame to find rows where 'col1' is within the range
# We use '&' for logical AND for multiple conditions


#filtered_df = N_df[(N_df[2] >= lower_bound) & (N_df[2] <= upper_bound)]
filtered_df = N_df[(N_df[2] >= lower_bound)]


print(f"DataFrame filtered for 'col1' values between {lower_bound} and {upper_bound}:")
display(filtered_df)

# Get the number of rows (entries) that satisfy the condition
count_in_range = len(filtered_df)

print(f"\nNumber of values in 'col1' between {lower_bound} and {upper_bound}: {count_in_range}")

DataFrame filtered for 'col1' values between 250 and 249:

           0  1    2           3
9    HopX1e   1  382  N-terminal
212  HopY1a   1  287  N-terminal
314  AvrE1d   1  257  N-terminal
318  AvrE1e   1  254  N-terminal
320  AvrE1k   1  258  N-terminal
322  AvrE1h   1  251  N-terminal
408  AvrE1c   1  354  N-terminal
414  AvrE1n   1  408  N-terminal
422  AvrE1x   1  270  N-terminal

Number of values in 'col1' between 250 and 249: 9

In [174]:
# Get unique entries from each column
set_A = set(not_in_both[0])
set_B = set(IDP_df[0])

# Find entries that are in A but not in B, or in B but not in A
# This is the symmetric difference (elements unique to each set)
not_in_both3 = list(set_A.symmetric_difference(set_B))

In [175]:
for item in not_in_both3:
    print(item)

HopAI1f
HopAU1b
HopBP1d
HopBS1a
HopB1c
HopAI1n
p
HopAG1n
1
I
HopAS1g
HopO1e
HopAZ1s
a
HopBR1a
HopAI1h
HopZ1k
HopAG1e
o
HopX1j
AvrRpm1g
HopG1f
HopZ1f
HopAI1l
HopBA1b
HopF3b
AvrPto1g
AvrPto1j
HopAZ1n
HopG1e
AvrE1q
H
HopAT1h
HopAH1aa

HopM1i