In [1]:
import pandas as pd

In [19]:
# Read the CSV file into a new DataFrame
new_df = pd.read_csv('/home/wenyuantong/Desktop/data/psytec_atr_pairs.csv')

# Display the first 5 rows of the new DataFrame
display(new_df.head())

                        IDR1                       IDR2   E_value
0  AvrRpm1d_N-terminal_1_100  AvrRpm1d_N-terminal_1_100 -0.099344
1  AvrRpm1d_N-terminal_1_100      HopI1e_Middle_180_300 -0.466960
2  AvrRpm1d_N-terminal_1_100  HopI1p_C-terminal_178_308 -0.920477
3  AvrRpm1d_N-terminal_1_100   HopAT1o_N-terminal_1_106 -0.826561
4  AvrRpm1d_N-terminal_1_100    AvrB2g_N-terminal_1_111 -1.394889

In [65]:
new_df = pd.read_csv('/home/wenyuantong/Desktop/data/psytec_atr_pairs.csv')

In [74]:
# Normalize each pair so that (A, B) and (B, A) are treated as the same
# We'll create a sorted tuple for each pair
def normalize_pair(row):
    return tuple(sorted([row['IDR1'], row['IDR2']]))

new_df['normalized_pair'] = new_df.apply(normalize_pair, axis=1)

print("\nDataFrame with normalized pairs:")
display(new_df)

# Get the unique normalized pairs
unique_matches = new_df['normalized_pair'].unique().tolist()

print("\nUnique bidirectional matches (normalized):")
print(unique_matches)

# rows corresponding to these unique matches
unique_rows_df = new_df.drop_duplicates(subset=['normalized_pair']).drop(columns=['normalized_pair'])

print("\nOriginal rows representing unique bidirectional matches:")
display(unique_rows_df)

DataFrame with normalized pairs:

,IDR1,IDR2,E_value,normalized_pair
0,AvrRpm1d_N-terminal_1_100,AvrRpm1d_N-terminal_1_100,-0.099344,"(AvrRpm1d_N-terminal_1_100, AvrRpm1d_N-termina..."
1,AvrRpm1d_N-terminal_1_100,HopI1e_Middle_180_300,-0.466960,"(AvrRpm1d_N-terminal_1_100, HopI1e_Middle_180_..."
2,AvrRpm1d_N-terminal_1_100,HopI1p_C-terminal_178_308,-0.920477,"(AvrRpm1d_N-terminal_1_100, HopI1p_C-terminal_..."
3,AvrRpm1d_N-terminal_1_100,HopAT1o_N-terminal_1_106,-0.826561,"(AvrRpm1d_N-terminal_1_100, HopAT1o_N-terminal..."
4,AvrRpm1d_N-terminal_1_100,AvrB2g_N-terminal_1_111,-1.394889,"(AvrB2g_N-terminal_1_111, AvrRpm1d_N-terminal_..."
...,...,...,...,...
268,HopY1e_Middle_106_220,AvrB2g_N-terminal_1_111,-0.188027,"(AvrB2g_N-terminal_1_111, HopY1e_Middle_106_220)"
269,HopZ1h_C-terminal_247_369,HopI1p_C-terminal_178_308,-0.483326,"(HopI1p_C-terminal_178_308, HopZ1h_C-terminal_..."
270,HopZ1h_C-terminal_247_369,HopAT1o_N-terminal_1_106,-0.670465,"(HopAT1o_N-terminal_1_106, HopZ1h_C-terminal_2..."
271,HopZ1h_C-terminal_247_369,AvrB2g_N-terminal_1_111,-0.837068,"(AvrB2g_N-terminal_1_111, HopZ1h_C-terminal_24..."
272,HopZ1h_C-terminal_247_369,HopR1d_C-terminal_1216_1324,-0.089348,"(HopR1d_C-terminal_1216_1324, HopZ1h_C-termina..."

Unique bidirectional matches (normalized):
[('AvrRpm1d_N-terminal_1_100', 'AvrRpm1d_N-terminal_1_100'), ('AvrRpm1d_N-terminal_1_100', 'HopI1e_Middle_180_300'), ('AvrRpm1d_N-terminal_1_100', 'HopI1p_C-terminal_178_308'), ('AvrRpm1d_N-terminal_1_100', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'AvrRpm1d_N-terminal_1_100'), ('AvrRpm1d_N-terminal_1_100', 'HopBP1g_N-terminal_1_130'), ('AvrRpm1d_N-terminal_1_100', 'HopBP1a_N-terminal_1_131'), ('AvrRpm1d_N-terminal_1_100', 'HopF1i_N-terminal_1_118'), ('AvrRpm1d_N-terminal_1_100', 'HopM1n_C-terminal_596_697'), ('AvrRpm1d_N-terminal_1_100', 'HopAG1n_IDP_1_111'), ('AvrRpm1d_N-terminal_1_100', 'HopR1d_C-terminal_1216_1324'), ('HopAR1g_N-terminal_1_141', 'HopI1e_Middle_180_300'), ('HopAT1o_N-terminal_1_106', 'HopI1e_Middle_180_300'), ('AvrB2g_N-terminal_1_111', 'HopI1e_Middle_180_300'), ('HopF1i_N-terminal_1_118', 'HopI1e_Middle_180_300'), ('HopAT1o_N-terminal_1_106', 'HopI1g_Middle_142_284'), ('AvrB2g_N-terminal_1_111', 'HopI1g_Middle_142_284'), ('HopI1p_C-terminal_178_308', 'HopZ1g_C-terminal_245_369'), ('HopI1p_C-terminal_178_308', 'HopZ1a_C-terminal_240_369'), ('HopAR1a_N-terminal_1_142', 'HopI1p_C-terminal_178_308'), ('HopAR1g_N-terminal_1_141', 'HopI1p_C-terminal_178_308'), ('HopAR1c_N-terminal_1_135', 'HopI1p_C-terminal_178_308'), ('HopAR1e_N-terminal_1_134', 'HopI1p_C-terminal_178_308'), ('HopAR1h_N-terminal_1_134', 'HopI1p_C-terminal_178_308'), ('HopAT1o_N-terminal_1_106', 'HopI1p_C-terminal_178_308'), ('AvrB2g_N-terminal_1_111', 'HopI1p_C-terminal_178_308'), ('HopI1p_C-terminal_178_308', 'HopR1c_Middle_1768_1895'), ('HopBP1b_N-terminal_1_131', 'HopI1p_C-terminal_178_308'), ('HopBP1a_N-terminal_1_131', 'HopI1p_C-terminal_178_308'), ('HopBP1f_N-terminal_1_131', 'HopI1p_C-terminal_178_308'), ('HopF1i_N-terminal_1_118', 'HopI1p_C-terminal_178_308'), ('HopAG1n_IDP_1_111', 'HopI1p_C-terminal_178_308'), ('HopI1p_C-terminal_178_308', 'HopZ1h_C-terminal_247_369'), ('HopAT1o_N-terminal_1_106', 'HopZ1g_C-terminal_245_369'), ('AvrB2g_N-terminal_1_111', 'HopZ1g_C-terminal_245_369'), ('HopR1d_C-terminal_1216_1324', 'HopZ1g_C-terminal_245_369'), ('HopAT1o_N-terminal_1_106', 'HopZ1a_C-terminal_240_369'), ('AvrB2g_N-terminal_1_111', 'HopZ1a_C-terminal_240_369'), ('HopAB1r_N-terminal_1_128', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAB1r_N-terminal_1_128'), ('HopAB1i_N-terminal_1_145', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAB1i_N-terminal_1_145'), ('HopAB1i_Middle_214_315', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAB1i_Middle_214_315'), ('HopAB1s_N-terminal_1_143', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAB1s_N-terminal_1_143'), ('HopAB1j_N-terminal_1_145', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAB1j_N-terminal_1_145'), ('HopAB1g_N-terminal_1_144', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAB1g_N-terminal_1_144'), ('HopAB1d_N-terminal_1_121', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAB1d_N-terminal_1_121'), ('HopAB1af_N-terminal_1_144', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAB1af_N-terminal_1_144'), ('HopAB1af_C-terminal_346_449', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAB1af_C-terminal_346_449'), ('HopAB1p_N-terminal_1_142', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAB1p_N-terminal_1_142'), ('HopAR1a_N-terminal_1_142', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAR1a_N-terminal_1_142'), ('HopAR1a_N-terminal_1_142', 'HopR1d_C-terminal_1216_1324'), ('HopAR1g_N-terminal_1_141', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAR1g_N-terminal_1_141'), ('HopAR1g_N-terminal_1_141', 'HopAU1a_C-terminal_614_731'), ('HopAR1g_N-terminal_1_141', 'HopBP1g_N-terminal_1_130'), ('HopAR1g_N-terminal_1_141', 'HopM1n_C-terminal_596_697'), ('HopAG1n_IDP_1_111', 'HopAR1g_N-terminal_1_141'), ('HopAR1g_N-terminal_1_141', 'HopR1d_C-terminal_1216_1324'), ('HopAR1c_N-terminal_1_135', 'HopR1d_C-terminal_1216_1324'), ('AvrB2g_N-terminal_1_111', 'HopAR1e_N-terminal_1_134'), ('HopAR1e_N-terminal_1_134', 'HopR1d_C-terminal_1216_1324'), ('HopAR1d_N-terminal_1_139', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAR1d_N-terminal_1_139'), ('AvrB2g_N-terminal_1_111', 'HopAR1h_N-terminal_1_134'), ('HopAR1h_N-terminal_1_134', 'HopR1d_C-terminal_1216_1324'), ('HopAT1b_N-terminal_1_133', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAT1b_N-terminal_1_133'), ('HopAT1o_N-terminal_1_106', 'HopAT1o_N-terminal_1_106'), ('AvrB2g_N-terminal_1_111', 'HopAT1o_N-terminal_1_106'), ('HopAT1o_N-terminal_1_106', 'HopY1f_Middle_98_218'), ('HopAT1o_N-terminal_1_106', 'HopY1c_Middle_106_221'), ('HopAT1o_N-terminal_1_106', 'HopAU1a_C-terminal_614_731'), ('HopAT1o_N-terminal_1_106', 'HopBP1b_N-terminal_1_131'), ('HopAT1o_N-terminal_1_106', 'HopBP1g_N-terminal_1_130'), ('HopAT1o_N-terminal_1_106', 'HopBP1c_N-terminal_1_130'), ('HopAT1o_N-terminal_1_106', 'HopBP1a_N-terminal_1_131'), ('HopAT1o_N-terminal_1_106', 'HopBP1f_N-terminal_1_131'), ('AvrE1p_N-terminal_1_150', 'HopAT1o_N-terminal_1_106'), ('AvrE1i_N-terminal_1_148', 'HopAT1o_N-terminal_1_106'), ('HopAT1o_N-terminal_1_106', 'HopF1i_N-terminal_1_118'), ('HopAT1o_N-terminal_1_106', 'HopM1n_C-terminal_596_697'), ('HopAB1ab_N-terminal_1_131', 'HopAT1o_N-terminal_1_106'), ('HopAB1q_N-terminal_1_129', 'HopAT1o_N-terminal_1_106'), ('HopAB1u_N-terminal_1_129', 'HopAT1o_N-terminal_1_106'), ('HopAB1v_N-terminal_1_143', 'HopAT1o_N-terminal_1_106'), ('HopAG1n_IDP_1_111', 'HopAT1o_N-terminal_1_106'), ('HopAT1h_IDP_1_122', 'HopAT1o_N-terminal_1_106'), ('HopAT1o_N-terminal_1_106', 'HopAZ1s_IDP_1_145'), ('HopAT1o_N-terminal_1_106', 'HopBR1a_IDP_1_133'), ('HopAT1o_N-terminal_1_106', 'HopR1d_C-terminal_1216_1324'), ('HopAT1o_N-terminal_1_106', 'HopZ1h_C-terminal_247_369'), ('AvrB2g_N-terminal_1_111', 'AvrB2g_N-terminal_1_111'), ('AvrB2g_N-terminal_1_111', 'HopW1b_C-terminal_795_914'), ('AvrB2g_N-terminal_1_111', 'HopY1f_Middle_98_218'), ('AvrB2g_N-terminal_1_111', 'HopY1c_Middle_106_221'), ('AvrB2g_N-terminal_1_111', 'HopAU1a_C-terminal_614_731'), ('AvrB2g_N-terminal_1_111', 'HopBP1b_N-terminal_1_131'), ('AvrB2g_N-terminal_1_111', 'HopBP1g_N-terminal_1_130'), ('AvrB2g_N-terminal_1_111', 'HopBP1c_N-terminal_1_130'), ('AvrB2g_N-terminal_1_111', 'HopBP1a_N-terminal_1_131'), ('AvrB2g_N-terminal_1_111', 'HopBP1f_N-terminal_1_131'), ('AvrB2g_N-terminal_1_111', 'HopF1i_N-terminal_1_118'), ('AvrB2g_N-terminal_1_111', 'HopM1n_C-terminal_596_697'), ('AvrB2g_N-terminal_1_111', 'HopAB1ab_N-terminal_1_131'), ('AvrB2g_N-terminal_1_111', 'HopAB1q_N-terminal_1_129'), ('AvrB2g_N-terminal_1_111', 'HopAB1u_N-terminal_1_129'), ('AvrB2g_N-terminal_1_111', 'HopAB1v_N-terminal_1_143'), ('AvrB2g_N-terminal_1_111', 'HopAG1n_IDP_1_111'), ('AvrB2g_N-terminal_1_111', 'HopAT1h_IDP_1_122'), ('AvrB2g_N-terminal_1_111', 'HopBR1a_IDP_1_133'), ('AvrB2g_N-terminal_1_111', 'HopR1d_C-terminal_1216_1324'), ('AvrB2g_N-terminal_1_111', 'HopY1e_Middle_106_220'), ('AvrB2g_N-terminal_1_111', 'HopZ1h_C-terminal_247_369'), ('HopR1c_Middle_1768_1895', 'HopR1d_C-terminal_1216_1324'), ('HopBP1b_N-terminal_1_131', 'HopR1d_C-terminal_1216_1324'), ('HopBP1g_N-terminal_1_130', 'HopF1i_N-terminal_1_118'), ('HopAG1n_IDP_1_111', 'HopBP1g_N-terminal_1_130'), ('HopBP1g_N-terminal_1_130', 'HopR1d_C-terminal_1216_1324'), ('HopBP1c_N-terminal_1_130', 'HopR1d_C-terminal_1216_1324'), ('HopBP1a_N-terminal_1_131', 'HopR1d_C-terminal_1216_1324'), ('HopBP1f_N-terminal_1_131', 'HopR1d_C-terminal_1216_1324'), ('HopF1i_N-terminal_1_118', 'HopF1i_N-terminal_1_118'), ('HopF1i_N-terminal_1_118', 'HopM1n_C-terminal_596_697'), ('HopAG1n_IDP_1_111', 'HopF1i_N-terminal_1_118'), ('HopF1i_N-terminal_1_118', 'HopR1d_C-terminal_1216_1324'), ('HopAG1n_IDP_1_111', 'HopM1n_C-terminal_596_697'), ('HopAG1n_IDP_1_111', 'HopAG1n_IDP_1_111'), ('HopAG1n_IDP_1_111', 'HopR1d_C-terminal_1216_1324'), ('HopR1d_C-terminal_1216_1324', 'HopZ1h_C-terminal_247_369')]

Original rows representing unique bidirectional matches:

                            IDR1                         IDR2   E_value
0      AvrRpm1d_N-terminal_1_100    AvrRpm1d_N-terminal_1_100 -0.099344
1      AvrRpm1d_N-terminal_1_100        HopI1e_Middle_180_300 -0.466960
2      AvrRpm1d_N-terminal_1_100    HopI1p_C-terminal_178_308 -0.920477
3      AvrRpm1d_N-terminal_1_100     HopAT1o_N-terminal_1_106 -0.826561
4      AvrRpm1d_N-terminal_1_100      AvrB2g_N-terminal_1_111 -1.394889
..                           ...                          ...       ...
220      HopF1i_N-terminal_1_118  HopR1d_C-terminal_1216_1324 -1.102721
226    HopM1n_C-terminal_596_697            HopAG1n_IDP_1_111 -0.013993
243            HopAG1n_IDP_1_111            HopAG1n_IDP_1_111 -0.295180
244            HopAG1n_IDP_1_111  HopR1d_C-terminal_1216_1324 -0.433029
267  HopR1d_C-terminal_1216_1324    HopZ1h_C-terminal_247_369 -0.079179

[139 rows x 3 columns]

In [20]:
new_df['prot1'] = new_df['IDR1'].str.split('_').str[0]

# Display the DataFrame with the new column
display(new_df.head())

                        IDR1                       IDR2   E_value     prot1
0  AvrRpm1d_N-terminal_1_100  AvrRpm1d_N-terminal_1_100 -0.099344  AvrRpm1d
1  AvrRpm1d_N-terminal_1_100      HopI1e_Middle_180_300 -0.466960  AvrRpm1d
2  AvrRpm1d_N-terminal_1_100  HopI1p_C-terminal_178_308 -0.920477  AvrRpm1d
3  AvrRpm1d_N-terminal_1_100   HopAT1o_N-terminal_1_106 -0.826561  AvrRpm1d
4  AvrRpm1d_N-terminal_1_100    AvrB2g_N-terminal_1_111 -1.394889  AvrRpm1d

In [21]:
new_df['prot2'] = new_df['IDR2'].str.split('_').str[0]

# Display the DataFrame with the new column
display(new_df.head())

,IDR1,IDR2,E_value,prot1,prot2
0,AvrRpm1d_N-terminal_1_100,AvrRpm1d_N-terminal_1_100,-0.099344,AvrRpm1d,AvrRpm1d
1,AvrRpm1d_N-terminal_1_100,HopI1e_Middle_180_300,-0.466960,AvrRpm1d,HopI1e
2,AvrRpm1d_N-terminal_1_100,HopI1p_C-terminal_178_308,-0.920477,AvrRpm1d,HopI1p
3,AvrRpm1d_N-terminal_1_100,HopAT1o_N-terminal_1_106,-0.826561,AvrRpm1d,HopAT1o
4,AvrRpm1d_N-terminal_1_100,AvrB2g_N-terminal_1_111,-1.394889,AvrRpm1d,AvrB2g

In [9]:
df = pd.read_excel('/home/wenyuantong/Desktop/data/PsyTEC Allele Master Info Sheet.xlsx',sheet_name="PsyTEC_alleles")

TypeError: 'Index' object is not callable

In [11]:
print("Column names in new_df:", df.columns.tolist())

Column names in new_df: ['PsyTEC_ID', 'Effector', 'Family', 'Subfamily', 'Frequency', 'Representative_effector', 'Chaperone', 'Strain', 'Contig', 'hrp_box', 'CDS', 'Construct_sequence', 'Barcode', 'Construct_length_nuc', 'CDS_length_nuc', 'Protein_sequence', 'Protein_length_aa', 'Predicted_MW_kDa', 'Immunoblot_DC3000', 'At_Col0_ETI_DC3000', 'Immunoblot_ES4326', 'At_Col0_ETI_ES4326', 'Cognate_NLR', 'Notes']

In [12]:
display(df.head())

,PsyTEC_ID,Effector,Family,Subfamily,Frequency,Representative_effector,Chaperone,Strain,Contig,hrp_box,...,CDS_length_nuc,Protein_sequence,Protein_length_aa,Predicted_MW_kDa,Immunoblot_DC3000,At_Col0_ETI_DC3000,Immunoblot_ES4326,At_Col0_ETI_ES4326,Cognate_NLR,Notes
0,1,HopX1a,HopX,HopX1,102.0,PgyICMP10448_HopX1a_1,NaN,NaN,NaN,GGAACCAACTCGCACGCAAAACCACACA,...,1143,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,380,41.00891,1,0,1,0,NaN,NaN
1,2,HopX1c,HopX,HopX1,69.0,PmpFTRS_U7_HopX1c_1,NaN,NaN,NaN,GGAACTGACCCGGCCCAAATGACGACATA,...,1155,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,384,41.41028,1,0,1,0,NaN,NaN
2,3,HopX1b,HopX,HopX1,72.0,PgcICMP4323_HopX1b_1,NaN,NaN,NaN,GGAACCAACCCGGACCAGGTGACGACTTA,...,1155,MKIHNAGVTGPLPSISNEGAGKAAQSSSTQPQSQPESHGPTPESSE...,384,41.40122,1,0,1,0,NaN,NaN
3,4,HopX1i,HopX,HopX1,5.0,PdpICMP13052_HopX1i_1,NaN,NaN,NaN,GGAACCAACTCGCACCTTCAGCCACACA,...,1155,MKIHNAGPSIPMPAPSIESAGKTAQSSLAQPQSQRATPVSPSETSD...,384,40.86556,1,1,1,1,ZAR1,NaN
4,5,HopX1e,HopX,HopX1,13.0,PpiH6E5_HopX1e_1,NaN,NaN,NaN,GGAACCAACTTGCGCGCAAAACCACACA,...,1149,MRIHSSGHGICAPVSSAETVEKAVQSSAQAQNEASHSGPSEHPESR...,382,40.92333,1,0,1,0,NaN,NaN

In [14]:
selected_columns = ['PsyTEC_ID', 'Effector' ]

# Create the sub-DataFrame by selecting the specified columns
df_id = df[selected_columns]

print(f"\nSub-DataFrame with selected columns: {selected_columns}")
display(df_id)

Sub-DataFrame with selected columns: ['PsyTEC_ID', 'Effector']

     PsyTEC_ID Effector
0            1   HopX1a
1            2   HopX1c
2            3   HopX1b
3            4   HopX1i
4            5   HopX1e
..         ...      ...
525        684   HopZ1h
526        685   HopZ1k
527        686   HopZ5a
528        687   HopZ5b
529        688   AvrB1b

[530 rows x 2 columns]

In [22]:
#merged_df = pd.merge(df_id, new_df, on='IDR1', how='inner')
merged_df = pd.merge(new_df, df_id, left_on='prot1', right_on='Effector', how='inner')

# Display the merged DataFrame
display(merged_df.head())

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID,Effector
0,AvrRpm1d_N-terminal_1_100,AvrRpm1d_N-terminal_1_100,-0.099344,AvrRpm1d,AvrRpm1d,20,AvrRpm1d
1,AvrRpm1d_N-terminal_1_100,HopI1e_Middle_180_300,-0.466960,AvrRpm1d,HopI1e,20,AvrRpm1d
2,AvrRpm1d_N-terminal_1_100,HopI1p_C-terminal_178_308,-0.920477,AvrRpm1d,HopI1p,20,AvrRpm1d
3,AvrRpm1d_N-terminal_1_100,HopAT1o_N-terminal_1_106,-0.826561,AvrRpm1d,HopAT1o,20,AvrRpm1d
4,AvrRpm1d_N-terminal_1_100,AvrB2g_N-terminal_1_111,-1.394889,AvrRpm1d,AvrB2g,20,AvrRpm1d

In [24]:
merged_df = merged_df.rename(columns={'PsyTEC_ID': 'PsyTEC_ID_1'})

# Display the DataFrame with the renamed column
display(merged_df.head())

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector
0,AvrRpm1d_N-terminal_1_100,AvrRpm1d_N-terminal_1_100,-0.099344,AvrRpm1d,AvrRpm1d,20,AvrRpm1d
1,AvrRpm1d_N-terminal_1_100,HopI1e_Middle_180_300,-0.466960,AvrRpm1d,HopI1e,20,AvrRpm1d
2,AvrRpm1d_N-terminal_1_100,HopI1p_C-terminal_178_308,-0.920477,AvrRpm1d,HopI1p,20,AvrRpm1d
3,AvrRpm1d_N-terminal_1_100,HopAT1o_N-terminal_1_106,-0.826561,AvrRpm1d,HopAT1o,20,AvrRpm1d
4,AvrRpm1d_N-terminal_1_100,AvrB2g_N-terminal_1_111,-1.394889,AvrRpm1d,AvrB2g,20,AvrRpm1d

In [25]:
#merged_df = pd.merge(df_id, new_df, on='IDR1', how='inner')
merged_df = pd.merge(merged_df, df_id, left_on='prot2', right_on='Effector', how='inner')

# Display the merged DataFrame
display(merged_df.head())

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector_x,PsyTEC_ID,Effector_y
0,AvrRpm1d_N-terminal_1_100,AvrRpm1d_N-terminal_1_100,-0.099344,AvrRpm1d,AvrRpm1d,20,AvrRpm1d,20,AvrRpm1d
1,AvrRpm1d_N-terminal_1_100,HopI1e_Middle_180_300,-0.466960,AvrRpm1d,HopI1e,20,AvrRpm1d,72,HopI1e
2,AvrRpm1d_N-terminal_1_100,HopI1p_C-terminal_178_308,-0.920477,AvrRpm1d,HopI1p,20,AvrRpm1d,86,HopI1p
3,AvrRpm1d_N-terminal_1_100,HopAT1o_N-terminal_1_106,-0.826561,AvrRpm1d,HopAT1o,20,AvrRpm1d,160,HopAT1o
4,AvrRpm1d_N-terminal_1_100,AvrB2g_N-terminal_1_111,-1.394889,AvrRpm1d,AvrB2g,20,AvrRpm1d,194,AvrB2g

In [26]:
merged_df = merged_df.rename(columns={'PsyTEC_ID': 'PsyTEC_ID_2'})

# Display the DataFrame with the renamed column
display(merged_df.head())

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector_x,PsyTEC_ID_2,Effector_y
0,AvrRpm1d_N-terminal_1_100,AvrRpm1d_N-terminal_1_100,-0.099344,AvrRpm1d,AvrRpm1d,20,AvrRpm1d,20,AvrRpm1d
1,AvrRpm1d_N-terminal_1_100,HopI1e_Middle_180_300,-0.466960,AvrRpm1d,HopI1e,20,AvrRpm1d,72,HopI1e
2,AvrRpm1d_N-terminal_1_100,HopI1p_C-terminal_178_308,-0.920477,AvrRpm1d,HopI1p,20,AvrRpm1d,86,HopI1p
3,AvrRpm1d_N-terminal_1_100,HopAT1o_N-terminal_1_106,-0.826561,AvrRpm1d,HopAT1o,20,AvrRpm1d,160,HopAT1o
4,AvrRpm1d_N-terminal_1_100,AvrB2g_N-terminal_1_111,-1.394889,AvrRpm1d,AvrB2g,20,AvrRpm1d,194,AvrB2g

In [32]:

# Example: filtering 'FirstColumn' for 'apple'
filtered_df = merged_df[(merged_df['prot1'] == 'AvrB2g') & (merged_df['prot2'] == 'AvrB2g')]
#filtered_df = merged_df[(merged_df['prot1'] == 'AvrB2g')]
# Display the filtered DataFrame
display(filtered_df)

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector_x,PsyTEC_ID_2,Effector_y
154,AvrB2g_N-terminal_1_111,AvrB2g_N-terminal_1_111,-3.169119,AvrB2g,AvrB2g,194,AvrB2g,194,AvrB2g

In [38]:
#display(merged_df)
sorted_df = merged_df.sort_values(by='E_value', ascending=True)

# Display the sorted DataFrame
display(sorted_df.head(10))

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector_x,PsyTEC_ID_2,Effector_y
154,AvrB2g_N-terminal_1_111,AvrB2g_N-terminal_1_111,-3.169119,AvrB2g,AvrB2g,194,AvrB2g,194,AvrB2g
28,HopI1p_C-terminal_178_308,HopR1c_Middle_1768_1895,-2.899410,HopI1p,HopR1c,86,HopI1p,283,HopR1c
181,HopR1c_Middle_1768_1895,HopI1p_C-terminal_178_308,-2.833011,HopR1c,HopI1p,283,HopR1c,86,HopI1p
26,HopI1p_C-terminal_178_308,HopAT1o_N-terminal_1_106,-2.825008,HopI1p,HopAT1o,86,HopI1p,160,HopAT1o
153,AvrB2g_N-terminal_1_111,HopAT1o_N-terminal_1_106,-2.551292,AvrB2g,HopAT1o,194,AvrB2g,160,HopAT1o
108,HopAT1o_N-terminal_1_106,AvrB2g_N-terminal_1_111,-2.436369,HopAT1o,AvrB2g,160,HopAT1o,194,AvrB2g
90,HopAT1o_N-terminal_1_106,HopI1p_C-terminal_178_308,-2.285884,HopAT1o,HopI1p,160,HopAT1o,86,HopI1p
27,HopI1p_C-terminal_178_308,AvrB2g_N-terminal_1_111,-2.107705,HopI1p,AvrB2g,86,HopI1p,194,AvrB2g
107,HopAT1o_N-terminal_1_106,HopAT1o_N-terminal_1_106,-2.107541,HopAT1o,HopAT1o,160,HopAT1o,160,HopAT1o
173,AvrB2g_N-terminal_1_111,HopR1d_C-terminal_1216_1324,-2.017218,AvrB2g,HopR1d,194,AvrB2g,658,HopR1d

In [34]:
df_yeast = pd.read_excel('/home/wenyuantong/Desktop/data/psytecY2H_MasterHits_New.xlsx',sheet_name="Sheet1")
display(df_yeast)

,Query,Gene,Score,array,batch,visualCheck,3_bioreps,biorep_batch,ori.strain.reconfm,ori.strain.reconfm.date,Notes
0,1,587,4.0,B,2024-03-07,NaN,NaN,NaN,NaN,NaN,NaN
1,1,471,3.0,A,2024-03-07,NaN,NaN,NaN,NaN,NaN,NaN
2,2,224,3.7,A,2024-03-07,NaN,N,2025-03-27 00:00:00,NaN,NaN,NaN
3,2,369,2.4,A,2024-03-07,NaN,N,2025-03-31 00:00:00,NaN,NaN,NaN
4,2,328,3.1,A,2024-03-07,NaN,N,2025-03-31 00:00:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
7251,pos,192,4.0,A,2025-09-05,NaN,NaN,NaN,NaN,NaN,NaN
7252,pos,366,4.0,A,2025-09-05,NaN,NaN,NaN,NaN,NaN,NaN
7253,pos,500A,4.0,B,2025-09-05,NaN,NaN,NaN,NaN,NaN,NaN
7254,pos,645,3.0,B,2025-09-05,NaN,NaN,NaN,NaN,NaN,NaN
7255,pos,RIN4,4.0,B,2025-09-05,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
qc_df_yeast = df_yeast[(df_yeast['Score'] == 4.0)]
display(qc_df_yeast)

,Query,Gene,Score,array,batch,visualCheck,3_bioreps,biorep_batch,ori.strain.reconfm,ori.strain.reconfm.date,Notes
0,1,587,4.0,B,2024-03-07,NaN,NaN,NaN,NaN,NaN,NaN
5,2,366,4.0,A,2024-03-07,NaN,Y,2025-04-11 00:00:00,NaN,NaN,NaN
6,2,471,4.0,A,2024-03-07,NaN,N,2025-04-15 00:00:00,NaN,NaN,NaN
7,2,587,4.0,B,2024-03-07,NaN,N,2025-05-05 00:00:00,NaN,NaN,NaN
8,2,675,4.0,B,2024-03-07,N,N,NaN,NaN,NaN,675 autoactivator/bg
...,...,...,...,...,...,...,...,...,...,...,...
7250,541,P05,4.0,B,2025-09-05,NaN,NaN,NaN,NaN,NaN,NaN
7251,pos,192,4.0,A,2025-09-05,NaN,NaN,NaN,NaN,NaN,NaN
7252,pos,366,4.0,A,2025-09-05,NaN,NaN,NaN,NaN,NaN,NaN
7253,pos,500A,4.0,B,2025-09-05,NaN,NaN,NaN,NaN,NaN,NaN
7255,pos,RIN4,4.0,B,2025-09-05,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
merged_df_multi_diff_names = pd.merge(
    sorted_df,
    qc_df_yeast,
    left_on=['PsyTEC_ID_1', 'PsyTEC_ID_2'],
    right_on=['Query', 'Gene'],
    how='inner'
)

# Display the merged DataFrame
display(merged_df_multi_diff_names.head())

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector_x,PsyTEC_ID_2,Effector_y,Query,Gene,Score,array,batch,visualCheck,3_bioreps,biorep_batch,ori.strain.reconfm,ori.strain.reconfm.date,Notes
0,AvrB2g_N-terminal_1_111,AvrB2g_N-terminal_1_111,-3.169119,AvrB2g,AvrB2g,194,AvrB2g,194,AvrB2g,194,194,4.0,A,2024-10-11,NaN,NaN,NaN,NaN,NaN,NaN
1,HopAT1o_N-terminal_1_106,HopAT1o_N-terminal_1_106,-2.107541,HopAT1o,HopAT1o,160,HopAT1o,160,HopAT1o,160,160,4.0,A,2024-05-30,NaN,NaN,NaN,NaN,NaN,NaN
2,HopAB1p_N-terminal_1_142,AvrB2g_N-terminal_1_111,-1.170817,HopAB1p,AvrB2g,141,HopAB1p,194,AvrB2g,141,194,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
3,HopAB1d_N-terminal_1_121,AvrB2g_N-terminal_1_111,-0.906890,HopAB1d,AvrB2g,135,HopAB1d,194,AvrB2g,135,194,4.0,A,2024-10-11,NaN,Y,2025-05-13 00:00:00,NaN,NaN,NaN
4,HopAB1p_N-terminal_1_142,HopAT1o_N-terminal_1_106,-0.774577,HopAB1p,HopAT1o,141,HopAB1p,160,HopAT1o,141,160,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B

In [40]:
display(merged_df_multi_diff_names)

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector_x,PsyTEC_ID_2,Effector_y,Query,Gene,Score,array,batch,visualCheck,3_bioreps,biorep_batch,ori.strain.reconfm,ori.strain.reconfm.date,Notes
0,AvrB2g_N-terminal_1_111,AvrB2g_N-terminal_1_111,-3.169119,AvrB2g,AvrB2g,194,AvrB2g,194,AvrB2g,194,194,4.0,A,2024-10-11,NaN,NaN,NaN,NaN,NaN,NaN
1,HopAT1o_N-terminal_1_106,HopAT1o_N-terminal_1_106,-2.107541,HopAT1o,HopAT1o,160,HopAT1o,160,HopAT1o,160,160,4.0,A,2024-05-30,NaN,NaN,NaN,NaN,NaN,NaN
2,HopAB1p_N-terminal_1_142,AvrB2g_N-terminal_1_111,-1.170817,HopAB1p,AvrB2g,141,HopAB1p,194,AvrB2g,141,194,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
3,HopAB1d_N-terminal_1_121,AvrB2g_N-terminal_1_111,-0.906890,HopAB1d,AvrB2g,135,HopAB1d,194,AvrB2g,135,194,4.0,A,2024-10-11,NaN,Y,2025-05-13 00:00:00,NaN,NaN,NaN
4,HopAB1p_N-terminal_1_142,HopAT1o_N-terminal_1_106,-0.774577,HopAB1p,HopAT1o,141,HopAB1p,160,HopAT1o,141,160,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
5,HopAB1q_N-terminal_1_129,AvrB2g_N-terminal_1_111,-0.755993,HopAB1q,AvrB2g,539,HopAB1q,194,AvrB2g,539,194,4.0,A,2024-12-06,NaN,Y,2025-08-23 00:00:00,NaN,NaN,NaN
6,HopY1f_Middle_98_218,HopAT1o_N-terminal_1_106,-0.396963,HopY1f,HopAT1o,245,HopY1f,160,HopAT1o,245,160,4.0,A,2025-06-05,NaN,NaN,NaN,NaN,NaN,NaN
7,HopY1c_Middle_106_221,AvrB2g_N-terminal_1_111,-0.283472,HopY1c,AvrB2g,246,HopY1c,194,AvrB2g,246,194,4.0,A,2025-06-13,NaN,NaN,NaN,NaN,NaN,NaN
8,HopY1f_Middle_98_218,AvrB2g_N-terminal_1_111,-0.210991,HopY1f,AvrB2g,245,HopY1f,194,AvrB2g,245,194,4.0,A,2025-06-05,NaN,NaN,NaN,NaN,NaN,NaN
9,HopY1e_Middle_106_220,AvrB2g_N-terminal_1_111,-0.188027,HopY1e,AvrB2g,681,HopY1e,194,AvrB2g,681,194,4.0,A,2024-12-21,NaN,NaN,NaN,NaN,NaN,RotationE
10,HopY1c_Middle_106_221,HopAT1o_N-terminal_1_106,-0.041860,HopY1c,HopAT1o,246,HopY1c,160,HopAT1o,246,160,4.0,A,2025-06-13,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
merged_df_multi_diff_names_1 = pd.merge(
    sorted_df,
    qc_df_yeast,
    left_on=['PsyTEC_ID_2', 'PsyTEC_ID_1'],
    right_on=['Query', 'Gene'],
    how='inner'
)

In [45]:
display(merged_df_multi_diff_names_1)

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector_x,PsyTEC_ID_2,Effector_y,Query,Gene,Score,array,batch,visualCheck,3_bioreps,biorep_batch,ori.strain.reconfm,ori.strain.reconfm.date,Notes
0,AvrB2g_N-terminal_1_111,AvrB2g_N-terminal_1_111,-3.169119,AvrB2g,AvrB2g,194,AvrB2g,194,AvrB2g,194,194,4.0,A,2024-10-11,NaN,NaN,NaN,NaN,NaN,NaN
1,HopAT1o_N-terminal_1_106,HopAT1o_N-terminal_1_106,-2.107541,HopAT1o,HopAT1o,160,HopAT1o,160,HopAT1o,160,160,4.0,A,2024-05-30,NaN,NaN,NaN,NaN,NaN,NaN
2,AvrB2g_N-terminal_1_111,HopAB1p_N-terminal_1_142,-0.915216,AvrB2g,HopAB1p,194,AvrB2g,141,HopAB1p,141,194,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
3,AvrB2g_N-terminal_1_111,HopAB1d_N-terminal_1_121,-0.831941,AvrB2g,HopAB1d,194,AvrB2g,135,HopAB1d,135,194,4.0,A,2024-10-11,NaN,Y,2025-05-13 00:00:00,NaN,NaN,NaN
4,AvrB2g_N-terminal_1_111,HopAB1q_N-terminal_1_129,-0.650505,AvrB2g,HopAB1q,194,AvrB2g,539,HopAB1q,539,194,4.0,A,2024-12-06,NaN,Y,2025-08-23 00:00:00,NaN,NaN,NaN
5,HopAT1o_N-terminal_1_106,HopAB1p_N-terminal_1_142,-0.578205,HopAT1o,HopAB1p,160,HopAT1o,141,HopAB1p,141,160,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
6,HopAT1o_N-terminal_1_106,HopY1f_Middle_98_218,-0.347753,HopAT1o,HopY1f,160,HopAT1o,245,HopY1f,245,160,4.0,A,2025-06-05,NaN,NaN,NaN,NaN,NaN,NaN
7,AvrB2g_N-terminal_1_111,HopY1c_Middle_106_221,-0.271254,AvrB2g,HopY1c,194,AvrB2g,246,HopY1c,246,194,4.0,A,2025-06-13,NaN,NaN,NaN,NaN,NaN,NaN
8,AvrB2g_N-terminal_1_111,HopY1f_Middle_98_218,-0.193554,AvrB2g,HopY1f,194,AvrB2g,245,HopY1f,245,194,4.0,A,2025-06-05,NaN,NaN,NaN,NaN,NaN,NaN
9,AvrB2g_N-terminal_1_111,HopY1e_Middle_106_220,-0.181487,AvrB2g,HopY1e,194,AvrB2g,681,HopY1e,681,194,4.0,A,2024-12-21,NaN,NaN,NaN,NaN,NaN,RotationE
10,HopAT1o_N-terminal_1_106,HopY1c_Middle_106_221,-0.038252,HopAT1o,HopY1c,160,HopAT1o,246,HopY1c,246,160,4.0,A,2025-06-13,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
concatenated_df_columns = pd.concat([merged_df_multi_diff_names, merged_df_multi_diff_names_1], axis=0, ignore_index=True).drop_duplicates()

print("Concatenated DataFrame (columns):")
display(concatenated_df_columns.head())
print("\nShape of concatenated_df_columns:", concatenated_df_columns.shape)

Concatenated DataFrame (columns):

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector_x,PsyTEC_ID_2,Effector_y,Query,Gene,Score,array,batch,visualCheck,3_bioreps,biorep_batch,ori.strain.reconfm,ori.strain.reconfm.date,Notes
0,AvrB2g_N-terminal_1_111,AvrB2g_N-terminal_1_111,-3.169119,AvrB2g,AvrB2g,194,AvrB2g,194,AvrB2g,194,194,4.0,A,2024-10-11,NaN,NaN,NaN,NaN,NaN,NaN
1,HopAT1o_N-terminal_1_106,HopAT1o_N-terminal_1_106,-2.107541,HopAT1o,HopAT1o,160,HopAT1o,160,HopAT1o,160,160,4.0,A,2024-05-30,NaN,NaN,NaN,NaN,NaN,NaN
2,HopAB1p_N-terminal_1_142,AvrB2g_N-terminal_1_111,-1.170817,HopAB1p,AvrB2g,141,HopAB1p,194,AvrB2g,141,194,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
3,HopAB1d_N-terminal_1_121,AvrB2g_N-terminal_1_111,-0.906890,HopAB1d,AvrB2g,135,HopAB1d,194,AvrB2g,135,194,4.0,A,2024-10-11,NaN,Y,2025-05-13 00:00:00,NaN,NaN,NaN
4,HopAB1p_N-terminal_1_142,HopAT1o_N-terminal_1_106,-0.774577,HopAB1p,HopAT1o,141,HopAB1p,160,HopAT1o,141,160,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B

Shape of concatenated_df_columns: (20, 20)

In [49]:
display(concatenated_df_columns)

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector_x,PsyTEC_ID_2,Effector_y,Query,Gene,Score,array,batch,visualCheck,3_bioreps,biorep_batch,ori.strain.reconfm,ori.strain.reconfm.date,Notes
0,AvrB2g_N-terminal_1_111,AvrB2g_N-terminal_1_111,-3.169119,AvrB2g,AvrB2g,194,AvrB2g,194,AvrB2g,194,194,4.0,A,2024-10-11,NaN,NaN,NaN,NaN,NaN,NaN
1,HopAT1o_N-terminal_1_106,HopAT1o_N-terminal_1_106,-2.107541,HopAT1o,HopAT1o,160,HopAT1o,160,HopAT1o,160,160,4.0,A,2024-05-30,NaN,NaN,NaN,NaN,NaN,NaN
2,HopAB1p_N-terminal_1_142,AvrB2g_N-terminal_1_111,-1.170817,HopAB1p,AvrB2g,141,HopAB1p,194,AvrB2g,141,194,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
3,HopAB1d_N-terminal_1_121,AvrB2g_N-terminal_1_111,-0.906890,HopAB1d,AvrB2g,135,HopAB1d,194,AvrB2g,135,194,4.0,A,2024-10-11,NaN,Y,2025-05-13 00:00:00,NaN,NaN,NaN
4,HopAB1p_N-terminal_1_142,HopAT1o_N-terminal_1_106,-0.774577,HopAB1p,HopAT1o,141,HopAB1p,160,HopAT1o,141,160,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
5,HopAB1q_N-terminal_1_129,AvrB2g_N-terminal_1_111,-0.755993,HopAB1q,AvrB2g,539,HopAB1q,194,AvrB2g,539,194,4.0,A,2024-12-06,NaN,Y,2025-08-23 00:00:00,NaN,NaN,NaN
6,HopY1f_Middle_98_218,HopAT1o_N-terminal_1_106,-0.396963,HopY1f,HopAT1o,245,HopY1f,160,HopAT1o,245,160,4.0,A,2025-06-05,NaN,NaN,NaN,NaN,NaN,NaN
7,HopY1c_Middle_106_221,AvrB2g_N-terminal_1_111,-0.283472,HopY1c,AvrB2g,246,HopY1c,194,AvrB2g,246,194,4.0,A,2025-06-13,NaN,NaN,NaN,NaN,NaN,NaN
8,HopY1f_Middle_98_218,AvrB2g_N-terminal_1_111,-0.210991,HopY1f,AvrB2g,245,HopY1f,194,AvrB2g,245,194,4.0,A,2025-06-05,NaN,NaN,NaN,NaN,NaN,NaN
9,HopY1e_Middle_106_220,AvrB2g_N-terminal_1_111,-0.188027,HopY1e,AvrB2g,681,HopY1e,194,AvrB2g,681,194,4.0,A,2024-12-21,NaN,NaN,NaN,NaN,NaN,RotationE
10,HopY1c_Middle_106_221,HopAT1o_N-terminal_1_106,-0.041860,HopY1c,HopAT1o,246,HopY1c,160,HopAT1o,246,160,4.0,A,2025-06-13,NaN,NaN,NaN,NaN,NaN,NaN
13,AvrB2g_N-terminal_1_111,HopAB1p_N-terminal_1_142,-0.915216,AvrB2g,HopAB1p,194,AvrB2g,141,HopAB1p,141,194,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
14,AvrB2g_N-terminal_1_111,HopAB1d_N-terminal_1_121,-0.831941,AvrB2g,HopAB1d,194,AvrB2g,135,HopAB1d,135,194,4.0,A,2024-10-11,NaN,Y,2025-05-13 00:00:00,NaN,NaN,NaN
15,AvrB2g_N-terminal_1_111,HopAB1q_N-terminal_1_129,-0.650505,AvrB2g,HopAB1q,194,AvrB2g,539,HopAB1q,539,194,4.0,A,2024-12-06,NaN,Y,2025-08-23 00:00:00,NaN,NaN,NaN
16,HopAT1o_N-terminal_1_106,HopAB1p_N-terminal_1_142,-0.578205,HopAT1o,HopAB1p,160,HopAT1o,141,HopAB1p,141,160,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
17,HopAT1o_N-terminal_1_106,HopY1f_Middle_98_218,-0.347753,HopAT1o,HopY1f,160,HopAT1o,245,HopY1f,245,160,4.0,A,2025-06-05,NaN,NaN,NaN,NaN,NaN,NaN
18,AvrB2g_N-terminal_1_111,HopY1c_Middle_106_221,-0.271254,AvrB2g,HopY1c,194,AvrB2g,246,HopY1c,246,194,4.0,A,2025-06-13,NaN,NaN,NaN,NaN,NaN,NaN
19,AvrB2g_N-terminal_1_111,HopY1f_Middle_98_218,-0.193554,AvrB2g,HopY1f,194,AvrB2g,245,HopY1f,245,194,4.0,A,2025-06-05,NaN,NaN,NaN,NaN,NaN,NaN
20,AvrB2g_N-terminal_1_111,HopY1e_Middle_106_220,-0.181487,AvrB2g,HopY1e,194,AvrB2g,681,HopY1e,681,194,4.0,A,2024-12-21,NaN,NaN,NaN,NaN,NaN,RotationE
21,HopAT1o_N-terminal_1_106,HopY1c_Middle_106_221,-0.038252,HopAT1o,HopY1c,160,HopAT1o,246,HopY1c,246,160,4.0,A,2025-06-13,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
#display(merged_df)
concatenated_df_columns_sorted_df = concatenated_df_columns.sort_values(by='E_value', ascending=True)

# Display the sorted DataFrame
display(concatenated_df_columns_sorted_df.head(10))

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector_x,PsyTEC_ID_2,Effector_y,Query,Gene,Score,array,batch,visualCheck,3_bioreps,biorep_batch,ori.strain.reconfm,ori.strain.reconfm.date,Notes
0,AvrB2g_N-terminal_1_111,AvrB2g_N-terminal_1_111,-3.169119,AvrB2g,AvrB2g,194,AvrB2g,194,AvrB2g,194,194,4.0,A,2024-10-11,NaN,NaN,NaN,NaN,NaN,NaN
1,HopAT1o_N-terminal_1_106,HopAT1o_N-terminal_1_106,-2.107541,HopAT1o,HopAT1o,160,HopAT1o,160,HopAT1o,160,160,4.0,A,2024-05-30,NaN,NaN,NaN,NaN,NaN,NaN
2,HopAB1p_N-terminal_1_142,AvrB2g_N-terminal_1_111,-1.170817,HopAB1p,AvrB2g,141,HopAB1p,194,AvrB2g,141,194,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
13,AvrB2g_N-terminal_1_111,HopAB1p_N-terminal_1_142,-0.915216,AvrB2g,HopAB1p,194,AvrB2g,141,HopAB1p,141,194,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
3,HopAB1d_N-terminal_1_121,AvrB2g_N-terminal_1_111,-0.906890,HopAB1d,AvrB2g,135,HopAB1d,194,AvrB2g,135,194,4.0,A,2024-10-11,NaN,Y,2025-05-13 00:00:00,NaN,NaN,NaN
14,AvrB2g_N-terminal_1_111,HopAB1d_N-terminal_1_121,-0.831941,AvrB2g,HopAB1d,194,AvrB2g,135,HopAB1d,135,194,4.0,A,2024-10-11,NaN,Y,2025-05-13 00:00:00,NaN,NaN,NaN
4,HopAB1p_N-terminal_1_142,HopAT1o_N-terminal_1_106,-0.774577,HopAB1p,HopAT1o,141,HopAB1p,160,HopAT1o,141,160,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B
5,HopAB1q_N-terminal_1_129,AvrB2g_N-terminal_1_111,-0.755993,HopAB1q,AvrB2g,539,HopAB1q,194,AvrB2g,539,194,4.0,A,2024-12-06,NaN,Y,2025-08-23 00:00:00,NaN,NaN,NaN
15,AvrB2g_N-terminal_1_111,HopAB1q_N-terminal_1_129,-0.650505,AvrB2g,HopAB1q,194,AvrB2g,539,HopAB1q,539,194,4.0,A,2024-12-06,NaN,Y,2025-08-23 00:00:00,NaN,NaN,NaN
16,HopAT1o_N-terminal_1_106,HopAB1p_N-terminal_1_142,-0.578205,HopAT1o,HopAB1p,160,HopAT1o,141,HopAB1p,141,160,4.0,A,2025-02-06,NaN,NaN,NaN,NaN,NaN,Rotation B

In [75]:
selected_columns = ['IDR1', 'IDR2', 'E_value', 'PsyTEC_ID_1', 'PsyTEC_ID_2', 'Effector_x', 'Effector_y', 'Score', 'array', 'batch']

# Create the sub-DataFrame by selecting the specified columns
df_final = concatenated_df_columns_sorted_df[selected_columns]

print(f"\nSub-DataFrame with selected columns: {selected_columns}")
display(df_final)

Sub-DataFrame with selected columns: ['IDR1', 'IDR2', 'E_value', 'PsyTEC_ID_1', 'PsyTEC_ID_2', 'Effector_x', 'Effector_y', 'Score', 'array', 'batch']

,IDR1,IDR2,E_value,PsyTEC_ID_1,PsyTEC_ID_2,Effector_x,Effector_y,Score,array,batch
0,AvrB2g_N-terminal_1_111,AvrB2g_N-terminal_1_111,-3.169119,194,194,AvrB2g,AvrB2g,4.0,A,2024-10-11
1,HopAT1o_N-terminal_1_106,HopAT1o_N-terminal_1_106,-2.107541,160,160,HopAT1o,HopAT1o,4.0,A,2024-05-30
2,HopAB1p_N-terminal_1_142,AvrB2g_N-terminal_1_111,-1.170817,141,194,HopAB1p,AvrB2g,4.0,A,2025-02-06
13,AvrB2g_N-terminal_1_111,HopAB1p_N-terminal_1_142,-0.915216,194,141,AvrB2g,HopAB1p,4.0,A,2025-02-06
3,HopAB1d_N-terminal_1_121,AvrB2g_N-terminal_1_111,-0.906890,135,194,HopAB1d,AvrB2g,4.0,A,2024-10-11
14,AvrB2g_N-terminal_1_111,HopAB1d_N-terminal_1_121,-0.831941,194,135,AvrB2g,HopAB1d,4.0,A,2024-10-11
4,HopAB1p_N-terminal_1_142,HopAT1o_N-terminal_1_106,-0.774577,141,160,HopAB1p,HopAT1o,4.0,A,2025-02-06
5,HopAB1q_N-terminal_1_129,AvrB2g_N-terminal_1_111,-0.755993,539,194,HopAB1q,AvrB2g,4.0,A,2024-12-06
15,AvrB2g_N-terminal_1_111,HopAB1q_N-terminal_1_129,-0.650505,194,539,AvrB2g,HopAB1q,4.0,A,2024-12-06
16,HopAT1o_N-terminal_1_106,HopAB1p_N-terminal_1_142,-0.578205,160,141,HopAT1o,HopAB1p,4.0,A,2025-02-06
6,HopY1f_Middle_98_218,HopAT1o_N-terminal_1_106,-0.396963,245,160,HopY1f,HopAT1o,4.0,A,2025-06-05
17,HopAT1o_N-terminal_1_106,HopY1f_Middle_98_218,-0.347753,160,245,HopAT1o,HopY1f,4.0,A,2025-06-05
7,HopY1c_Middle_106_221,AvrB2g_N-terminal_1_111,-0.283472,246,194,HopY1c,AvrB2g,4.0,A,2025-06-13
18,AvrB2g_N-terminal_1_111,HopY1c_Middle_106_221,-0.271254,194,246,AvrB2g,HopY1c,4.0,A,2025-06-13
8,HopY1f_Middle_98_218,AvrB2g_N-terminal_1_111,-0.210991,245,194,HopY1f,AvrB2g,4.0,A,2025-06-05
19,AvrB2g_N-terminal_1_111,HopY1f_Middle_98_218,-0.193554,194,245,AvrB2g,HopY1f,4.0,A,2025-06-05
9,HopY1e_Middle_106_220,AvrB2g_N-terminal_1_111,-0.188027,681,194,HopY1e,AvrB2g,4.0,A,2024-12-21
20,AvrB2g_N-terminal_1_111,HopY1e_Middle_106_220,-0.181487,194,681,AvrB2g,HopY1e,4.0,A,2024-12-21
10,HopY1c_Middle_106_221,HopAT1o_N-terminal_1_106,-0.041860,246,160,HopY1c,HopAT1o,4.0,A,2025-06-13
21,HopAT1o_N-terminal_1_106,HopY1c_Middle_106_221,-0.038252,160,246,HopAT1o,HopY1c,4.0,A,2025-06-13

In [53]:
selected_columns = ['PsyTEC_ID', 'Family' ]

# Create the sub-DataFrame by selecting the specified columns
df_fam = df[selected_columns]

print(f"\nSub-DataFrame with selected columns: {selected_columns}")
display(df_fam)

Sub-DataFrame with selected columns: ['PsyTEC_ID', 'Family']

     PsyTEC_ID Family
0            1   HopX
1            2   HopX
2            3   HopX
3            4   HopX
4            5   HopX
..         ...    ...
525        684   HopZ
526        685   HopZ
527        686   HopZ
528        687   HopZ
529        688   AvrB

[530 rows x 2 columns]

In [58]:
merged_df_multi_diff_names_1 = pd.merge(
    sorted_df,
    df_fam,
    left_on=['PsyTEC_ID_1'],
    right_on=['PsyTEC_ID'],
    how='inner'
)

In [59]:
display(merged_df_multi_diff_names_1)

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector_x,PsyTEC_ID_2,Effector_y,PsyTEC_ID,Family
0,AvrB2g_N-terminal_1_111,AvrB2g_N-terminal_1_111,-3.169119,AvrB2g,AvrB2g,194,AvrB2g,194,AvrB2g,194,AvrB
1,HopI1p_C-terminal_178_308,HopR1c_Middle_1768_1895,-2.899410,HopI1p,HopR1c,86,HopI1p,283,HopR1c,86,HopI
2,HopR1c_Middle_1768_1895,HopI1p_C-terminal_178_308,-2.833011,HopR1c,HopI1p,283,HopR1c,86,HopI1p,283,HopR
3,HopI1p_C-terminal_178_308,HopAT1o_N-terminal_1_106,-2.825008,HopI1p,HopAT1o,86,HopI1p,160,HopAT1o,86,HopI
4,AvrB2g_N-terminal_1_111,HopAT1o_N-terminal_1_106,-2.551292,AvrB2g,HopAT1o,194,AvrB2g,160,HopAT1o,194,AvrB
...,...,...,...,...,...,...,...,...,...,...,...
268,HopR1d_C-terminal_1216_1324,HopBP1c_N-terminal_1_130,-0.031332,HopR1d,HopBP1c,658,HopR1d,403,HopBP1c,658,HopR
269,HopZ1g_C-terminal_245_369,HopR1d_C-terminal_1216_1324,-0.029158,HopZ1g,HopR1d,125,HopZ1g,658,HopR1d,125,HopZ
270,HopR1d_C-terminal_1216_1324,HopZ1g_C-terminal_245_369,-0.025426,HopR1d,HopZ1g,658,HopR1d,125,HopZ1g,658,HopR
271,HopAG1n_IDP_1_111,HopM1n_C-terminal_596_697,-0.015228,HopAG1n,HopM1n,550,HopAG1n,481,HopM1n,550,HopAG
272,HopM1n_C-terminal_596_697,HopAG1n_IDP_1_111,-0.013993,HopM1n,HopAG1n,481,HopM1n,550,HopAG1n,481,HopM

In [60]:
merged_df_multi_diff_names_1 = pd.merge(
    merged_df_multi_diff_names_1,
    df_fam,
    left_on=['PsyTEC_ID_2'],
    right_on=['PsyTEC_ID'],
    how='inner'
)

In [64]:
display(merged_df_multi_diff_names_1)

,IDR1,IDR2,E_value,prot1,prot2,PsyTEC_ID_1,Effector_x,PsyTEC_ID_2,Effector_y,PsyTEC_ID_x,Family_x,PsyTEC_ID_y,Family_y
0,AvrB2g_N-terminal_1_111,AvrB2g_N-terminal_1_111,-3.169119,AvrB2g,AvrB2g,194,AvrB2g,194,AvrB2g,194,AvrB,194,AvrB
1,HopI1p_C-terminal_178_308,HopR1c_Middle_1768_1895,-2.899410,HopI1p,HopR1c,86,HopI1p,283,HopR1c,86,HopI,283,HopR
2,HopR1c_Middle_1768_1895,HopI1p_C-terminal_178_308,-2.833011,HopR1c,HopI1p,283,HopR1c,86,HopI1p,283,HopR,86,HopI
3,HopI1p_C-terminal_178_308,HopAT1o_N-terminal_1_106,-2.825008,HopI1p,HopAT1o,86,HopI1p,160,HopAT1o,86,HopI,160,HopAT
4,AvrB2g_N-terminal_1_111,HopAT1o_N-terminal_1_106,-2.551292,AvrB2g,HopAT1o,194,AvrB2g,160,HopAT1o,194,AvrB,160,HopAT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,HopR1d_C-terminal_1216_1324,HopBP1c_N-terminal_1_130,-0.031332,HopR1d,HopBP1c,658,HopR1d,403,HopBP1c,658,HopR,403,HopBP
269,HopZ1g_C-terminal_245_369,HopR1d_C-terminal_1216_1324,-0.029158,HopZ1g,HopR1d,125,HopZ1g,658,HopR1d,125,HopZ,658,HopR
270,HopR1d_C-terminal_1216_1324,HopZ1g_C-terminal_245_369,-0.025426,HopR1d,HopZ1g,658,HopR1d,125,HopZ1g,658,HopR,125,HopZ
271,HopAG1n_IDP_1_111,HopM1n_C-terminal_596_697,-0.015228,HopAG1n,HopM1n,550,HopAG1n,481,HopM1n,550,HopAG,481,HopM
272,HopM1n_C-terminal_596_697,HopAG1n_IDP_1_111,-0.013993,HopM1n,HopAG1n,481,HopM1n,550,HopAG1n,481,HopM,550,HopAG

In [63]:
print("Value counts for 'FirstColumn':")
display(merged_df_multi_diff_names_1['Family_x'].value_counts())

# Count instances for 'Column2'
print("\nValue counts for 'Column2':")
display(merged_df_multi_diff_names_1['Family_y'].value_counts())

Value counts for 'FirstColumn':

Family_x
HopAT     48
AvrB      45
HopAB     28
HopI      24
HopBP     23
HopAR     23
HopR      20
AvrRpm    11
HopZ      11
HopF      10
HopAG     10
HopM       6
HopY       5
HopAU      3
HopBR      2
AvrE       2
HopAZ      1
HopW       1
Name: count, dtype: int64

Value counts for 'Column2':

Family_y
HopAT     48
AvrB      45
HopAB     28
HopI      24
HopBP     23
HopAR     23
HopR      20
AvrRpm    11
HopZ      11
HopF      10
HopAG     10
HopM       6
HopY       5
HopAU      3
HopBR      2
AvrE       2
HopAZ      1
HopW       1
Name: count, dtype: int64

In [78]:
#unique_rows_df


# Filter df_A to keep rows where 'Value_A' is present in df_B['Value_B']
# This finds elements of 'Value_A' that exist in 'Value_B'
filtered_df_A = df_final[df_final['IDR1'].isin(['IDR1'])]
filtered_df_A = df_final[df_final['IDR1'].isin(['IDR1'])]

print("\nDataFrame A filtered: rows where 'Value_A' is present in df_B['Value_B']:")
display(filtered_df_A)

DataFrame A filtered: rows where 'Value_A' is present in df_B['Value_B']:

                         IDR1                         IDR2   E_value
54   HopAB1d_N-terminal_1_121     HopAT1o_N-terminal_1_106 -0.445521
55   HopAB1d_N-terminal_1_121      AvrB2g_N-terminal_1_111 -0.906890
60   HopAB1p_N-terminal_1_142     HopAT1o_N-terminal_1_106 -0.774577
61   HopAB1p_N-terminal_1_142      AvrB2g_N-terminal_1_111 -1.170817
107  HopAT1o_N-terminal_1_106     HopAT1o_N-terminal_1_106 -2.107541
108  HopAT1o_N-terminal_1_106      AvrB2g_N-terminal_1_111 -2.436369
109  HopAT1o_N-terminal_1_106         HopY1f_Middle_98_218 -0.347753
110  HopAT1o_N-terminal_1_106        HopY1c_Middle_106_221 -0.038252
111  HopAT1o_N-terminal_1_106   HopAU1a_C-terminal_614_731 -1.399814
112  HopAT1o_N-terminal_1_106     HopBP1b_N-terminal_1_131 -0.887808
113  HopAT1o_N-terminal_1_106     HopBP1g_N-terminal_1_130 -1.360424
114  HopAT1o_N-terminal_1_106     HopBP1c_N-terminal_1_130 -0.794274
115  HopAT1o_N-terminal_1_106     HopBP1a_N-terminal_1_131 -0.944718
116  HopAT1o_N-terminal_1_106     HopBP1f_N-terminal_1_131 -0.436300
117  HopAT1o_N-terminal_1_106      AvrE1p_N-terminal_1_150 -0.256834
118  HopAT1o_N-terminal_1_106      AvrE1i_N-terminal_1_148 -0.189031
119  HopAT1o_N-terminal_1_106      HopF1i_N-terminal_1_118 -1.017970
120  HopAT1o_N-terminal_1_106    HopM1n_C-terminal_596_697 -1.081366
121  HopAT1o_N-terminal_1_106    HopAB1ab_N-terminal_1_131 -0.519257
122  HopAT1o_N-terminal_1_106     HopAB1q_N-terminal_1_129 -0.175282
123  HopAT1o_N-terminal_1_106     HopAB1u_N-terminal_1_129 -0.131599
124  HopAT1o_N-terminal_1_106     HopAB1v_N-terminal_1_143 -0.414090
125  HopAT1o_N-terminal_1_106            HopAG1n_IDP_1_111 -1.441107
126  HopAT1o_N-terminal_1_106            HopAT1h_IDP_1_122 -1.074782
127  HopAT1o_N-terminal_1_106            HopAZ1s_IDP_1_145 -0.100722
128  HopAT1o_N-terminal_1_106            HopBR1a_IDP_1_133 -1.080994
129  HopAT1o_N-terminal_1_106  HopR1d_C-terminal_1216_1324 -1.845001
130  HopAT1o_N-terminal_1_106    HopZ1h_C-terminal_247_369 -0.577799
154   AvrB2g_N-terminal_1_111      AvrB2g_N-terminal_1_111 -3.169119
155   AvrB2g_N-terminal_1_111    HopW1b_C-terminal_795_914 -0.053820
156   AvrB2g_N-terminal_1_111         HopY1f_Middle_98_218 -0.193554
157   AvrB2g_N-terminal_1_111        HopY1c_Middle_106_221 -0.271254
158   AvrB2g_N-terminal_1_111   HopAU1a_C-terminal_614_731 -1.129432
159   AvrB2g_N-terminal_1_111     HopBP1b_N-terminal_1_131 -1.236405
160   AvrB2g_N-terminal_1_111     HopBP1g_N-terminal_1_130 -1.539235
161   AvrB2g_N-terminal_1_111     HopBP1c_N-terminal_1_130 -1.153294
162   AvrB2g_N-terminal_1_111     HopBP1a_N-terminal_1_131 -1.348519
163   AvrB2g_N-terminal_1_111     HopBP1f_N-terminal_1_131 -0.797340
164   AvrB2g_N-terminal_1_111      HopF1i_N-terminal_1_118 -1.747060
165   AvrB2g_N-terminal_1_111    HopM1n_C-terminal_596_697 -1.375146
166   AvrB2g_N-terminal_1_111    HopAB1ab_N-terminal_1_131 -0.818155
167   AvrB2g_N-terminal_1_111     HopAB1q_N-terminal_1_129 -0.650505
168   AvrB2g_N-terminal_1_111     HopAB1u_N-terminal_1_129 -0.557234
169   AvrB2g_N-terminal_1_111     HopAB1v_N-terminal_1_143 -0.761204
170   AvrB2g_N-terminal_1_111            HopAG1n_IDP_1_111 -1.620454
171   AvrB2g_N-terminal_1_111            HopAT1h_IDP_1_122 -1.147230
172   AvrB2g_N-terminal_1_111            HopBR1a_IDP_1_133 -1.014607
173   AvrB2g_N-terminal_1_111  HopR1d_C-terminal_1216_1324 -2.017218
174   AvrB2g_N-terminal_1_111        HopY1e_Middle_106_220 -0.181487
175   AvrB2g_N-terminal_1_111    HopZ1h_C-terminal_247_369 -0.755403

In [80]:
unique_rows_df2 = pd.merge(
    unique_rows_df,
    df_final,
    left_on=['IDR1', 'IDR2'],
    right_on=['IDR1', 'IDR2'],
    how='inner'
)

In [81]:
unique_rows_df2

,IDR1,IDR2,E_value_x,E_value_y,PsyTEC_ID_1,PsyTEC_ID_2,Effector_x,Effector_y,Score,array,batch
0,HopAB1d_N-terminal_1_121,AvrB2g_N-terminal_1_111,-0.906890,-0.906890,135,194,HopAB1d,AvrB2g,4.0,A,2024-10-11
1,HopAB1p_N-terminal_1_142,HopAT1o_N-terminal_1_106,-0.774577,-0.774577,141,160,HopAB1p,HopAT1o,4.0,A,2025-02-06
2,HopAB1p_N-terminal_1_142,AvrB2g_N-terminal_1_111,-1.170817,-1.170817,141,194,HopAB1p,AvrB2g,4.0,A,2025-02-06
3,HopAT1o_N-terminal_1_106,HopAT1o_N-terminal_1_106,-2.107541,-2.107541,160,160,HopAT1o,HopAT1o,4.0,A,2024-05-30
4,HopAT1o_N-terminal_1_106,HopY1f_Middle_98_218,-0.347753,-0.347753,160,245,HopAT1o,HopY1f,4.0,A,2025-06-05
5,HopAT1o_N-terminal_1_106,HopY1c_Middle_106_221,-0.038252,-0.038252,160,246,HopAT1o,HopY1c,4.0,A,2025-06-13
6,AvrB2g_N-terminal_1_111,AvrB2g_N-terminal_1_111,-3.169119,-3.169119,194,194,AvrB2g,AvrB2g,4.0,A,2024-10-11
7,AvrB2g_N-terminal_1_111,HopY1f_Middle_98_218,-0.193554,-0.193554,194,245,AvrB2g,HopY1f,4.0,A,2025-06-05
8,AvrB2g_N-terminal_1_111,HopY1c_Middle_106_221,-0.271254,-0.271254,194,246,AvrB2g,HopY1c,4.0,A,2025-06-13
9,AvrB2g_N-terminal_1_111,HopAB1q_N-terminal_1_129,-0.650505,-0.650505,194,539,AvrB2g,HopAB1q,4.0,A,2024-12-06
10,AvrB2g_N-terminal_1_111,HopY1e_Middle_106_220,-0.181487,-0.181487,194,681,AvrB2g,HopY1e,4.0,A,2024-12-21